### ISSUE TITLE
Bruk av deprecated React.PropTypes gir error i React 16

### ISSUE THREAD

**Issue by otenav** [navikt/aksel#100]
Når vi nå snart går over til react v16 må disse fikses. 

Har foreløpig funnet bruk av deprecated React.PropTypes i skjemaelement-feilmelding.js

**Comment by nutgaard** [comment]
Dette er alt løst for alle modulene, men ser ut til at React.PropTypes ble reintrodusert i #93

**Comment by nutgaard** [comment]
Løst i #101
