### ISSUE TITLE
Max-width på tekstinnhold i Alertstriper

### ISSUE THREAD

**Issue by erlendev** [navikt/aksel#103]
Alertstriper tar opp 100% bredde innenfor sin container, men det er ikke ønskelig at teksten skal strekke seg like langt ut. Maks 85 tegn per linje er hovedregelen - eller rundt ~608px/152em maksbredde. Tilsvarende regel gjelder ikke for mobilenheter ettersom lesbarheten her er en annen. Så tilpasning til desktop i første omgang.

**Comment by nutgaard** [comment]
feature, not a bug imho. :P 
Størrelsen og evt. plassering av komponenten bør styres av brukeren av komponenten.

**Comment by erlendev** [comment]
Sånn jeg forsto det så skulle vi ikke endre på at størrelsen på Alertstripe tar opp 100% bredde - kun selve Alertstripe-komponenten sine childrens max-width. Men når jeg ser det in action så ser det jo litt snodig ut med en 100% container i det tilfellet, ihvertfall når teksten er venstrestilt. Midtstilt brukes også i noen tilfeller, skal sies. Skal få avklart det her før vi gjør noe. :)

Forøvrig enig i at vi ikke skal sette noen maksbredde på selve Alertstripen.

**Comment by erlendev** [comment]
Har fått avklart, og det er tilfeller av at Alertstripe blir så bred og med så mye tekst at den må brekkes (for lesbarhetens skyld). Assigner denne på meg selv.
