### ISSUE TITLE
[BUG] Knapper virker ikke uten ekstra oppsett i Eslint config

### ISSUE THREAD

**Issue by w3bdesign** [navikt/aksel#1039]
## Hvilken av tjenestene våre gjelder det?

- [x] `Komponenter`
- [ ] `Stiler`
- [ ] `Ikoner`
- [ ] `Annet`

## Beskriv feilen/problemet

Forsøker å installere knapper via 

`npm install classnames lodash.throttle nav-frontend-core nav-frontend-js-utils nav-frontend-knapper nav-frontend-knapper-style nav-frontend-typografi-style prop-types react --save` 

men får følgende feilmelding:

` Line 6:28:  'nav-frontend-knapper' should be listed in the project's dependencies. Run 'npm i -S nav-frontend-knapper' to add it  import/no-extraneous-dependencies`

Har ikke hatt samme problem med noen andre komponenter, derfor tror jeg det kan være en bug.

Klarer til slutt å fikse det med å endre .eslintrc.json og legge til: 

`
"settings": {
    "import/resolver": {
      "node": {}
    }
  }
`

## Steg for å reprodusere problemet

1. Sett opp Create React App med Typescript template
2. Kjør `npm install classnames lodash.throttle nav-frontend-core nav-frontend-js-utils nav-frontend-knapper nav-frontend-knapper-style nav-frontend-typografi-style prop-types react --save`
3. Start React med `npm run start`
4. Se feilmelding

## Eksempel/Tilleggsinformasjon

![image](https://user-images.githubusercontent.com/45217974/111057320-d50fd200-8486-11eb-9f0a-175124a3db5a.png)

**Comment by KenAJoh** [comment]
Har prøvd å reprodusere feilen, men fungerer fint for meg. Kan ha noe med Node og npm versjon å gjøre, eller kanskje en global eslint installasjon.

Hvilken versjon av Npm og Node er installert? Evt er Eslint installert globalt?

**Comment by w3bdesign** [comment]
@KenAJoh 

node --version v12.20.1

npm --version 6.14.11

Dette er min devDependencies:

```

"devDependencies": {
    "@types/react-html-parser": "^2.0.1",
    "@types/styled-components": "^5.1.9",
    "@typescript-eslint/eslint-plugin": "^4.18.0",
    "@typescript-eslint/parser": "^4.18.0",
    "eslint": "^7.22.0",
    "eslint-config-airbnb": "^18.2.1",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-react": "^7.22.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "prettier": "^2.2.1",
    "stylelint": "^13.12.0",
    "stylelint-config-standard": "^21.0.0"
  }

```

eslint --version
'eslint' is not recognized as an internal or external command,
operable program or batch file.

Så ser ut som at den bruker lokal versjon.

Her er min .eslintrc.json fil:

```

{
  "env": {
    "browser": true,
    "es2021": true
  },
  "extends": ["plugin:react/recommended", "airbnb"],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": 12,
    "sourceType": "module"
  },
  "plugins": ["react", "@typescript-eslint"],
  "rules": {
    "react/jsx-filename-extension": [1, { "extensions": [".ts", ".tsx"] }],
    "no-use-before-define": "off",
    "@typescript-eslint/no-use-before-define": ["error"],
    "import/extensions": "off"
  },
  "overrides": [
    {
      "files": ["*.ts", "*.tsx"],
      "extends": [
        "plugin:@typescript-eslint/eslint-recommended",
        "plugin:@typescript-eslint/recommended",
        "plugin:import/typescript"
      ],
      "parser": "@typescript-eslint/parser",
      "plugins": ["@typescript-eslint"]
    }
  ],
  "settings": {
    "import/resolver": {
      "node": {}
    }
  }
}

```

**Comment by KenAJoh** [comment]
Hei, er dette fortsatt et problem? Vil tro dette er en one-off lokal bug så closer issuet, er bare å re-open hvis dette fortsatt er et problem.

**Comment by w3bdesign** [comment]
Ja, dette er et problem, men har ikke testet mer etter at jeg oppgraderte Node og Npm til nyeste versjon.
