### ISSUE TITLE
Unresolved peerDep i nav-frontend-js-utils\lib til lodash.throttle

### ISSUE THREAD

**Issue by abjolseth** [navikt/aksel#106]
Failed to compile
./node_modules/nav-frontend-js-utils/lib/eventThrottler.js
Module not found: Can't resolve 'lodash.throttle' in 'C:\Users\B150245\Dev\NAV\GitHub\melosys-web-proto\node_modules\nav-frontend-js-utils\lib'

**Comment by nutgaard** [comment]
Prøv å kjør `npm i` først

**Comment by erlendev** [comment]
Går utifra at denne kan lukkes @abjolseth. Gjenåpne dersom `npm i` ikke løste problemet.

**Comment by abjolseth** [comment]
Closed Ok. Har pratet med @nutgaard om dependency strategien.
