### ISSUE TITLE
[NEW] Base-versjon av @navikt/ds-react Popover

### ISSUE THREAD

**Issue by KenAJoh** [navikt/aksel#1080]
## Beskriv forespørselen

Ønskes en base-versjon av Popover i `@navikt/ds-react`

## Hvilken funksjon vil dette har for bruker?

Man kan da posisjonere popover manuelt og popover kobles da ikke til et spesifikt element

## Eksempler/Tilleggsinformasjon 

Typiskt eksempel er her der popover sin plassering ønskes at skal være statisk selv om man trykker på forskjellige elementer. 

<img width="1199" alt="Screenshot 2021-04-27 at 12 17 29" src="https://user-images.githubusercontent.com/26967723/116226029-cc334100-a752-11eb-90b1-4059bfe9785d.png">

**Comment by andnorda** [comment]
Hva tenker du er fordelen med å ha en base-versjon av Popover i `@navikt/ds-react` framfor å anbefale folk å bruke popperjs direkte?

**Comment by KenAJoh** [comment]
I en base-versjon brukes ikke popperjs i komponenten. Det brukeren er ute etter er open/close + keydown handlingen som er implementert i Popover + stylingen. Bruker kan ganske lett lage en slik løsning selv ved hjelp av stilpakken, men tenker det vil være bedre å tilby den fra oss da vi passer på at diverse stiler og UU er i orden.
Laget et forslag her: https://github.com/navikt/nav-frontend-moduler/blob/popover-base-vnext/%40navikt/ds-react/src/popover/PopoverBase.tsx

**Comment by KenAJoh** [comment]
Lukker denne da vi ikke ser at dette er en komponent/løsning vi ønsker inn i systemet for nå.
