### ISSUE TITLE
[BUG] Accordion TypeScript Props

### ISSUE THREAD

**Issue by ivoiv** [navikt/aksel#1121]
## Hvilken av tjenestene våre gjelder det?

- [X] `Komponenter`
- [ ] `Stiler`
- [ ] `Ikoner`
- [ ] `Annet`

https://github.com/navikt/nav-frontend-moduler/blob/master/%40navikt/ds-react/src/accordion/Accordion.tsx

## Beskriv feilen/problemet
 
Feil typing på Accordion.
``` <Accordion heading="Hello" type="button">Hi</Accordion>``` gir feil på `type`
``` Property 'type' does not exist on type 'IntrinsicAttributes & AccordionProps & RefAttributes<HTMLDivElement>'.```
 
AccordionProps er definert som
 ```
export interface AccordionProps  extends React.HTMLAttributes<HTMLButtonElement>
```

mens Accordion er definert som
```
const Accordion = forwardRef<HTMLDivElement, AccordionProps>
```

Dette gjør at Div props tar over for Button props i den eksponerte typen.

**Comment by KenAJoh** [comment]
Hei, har laget en PR på det for å fikse dette. Tenker det gir mening for oss å bare sette ref på `button` elementet istedenfor, så vi ender da opp med: 
`const Accordion = forwardRef<HTMLButtonElement, AccordionProps>`
