### ISSUE TITLE
Knapper mangler font-family

### ISSUE THREAD

**Issue by otenav** [navikt/aksel#113]
I designmalen har knappene Source Sans Pro. I nav-frontend-knapper defineres derimot ikke font-family på knapp. For å få riktig font, må derfor alle som bruker knappene override .knapp og legge til font-family, eventuelt må man legge til en egen custom klasse, feks. .knapp--with-sourcesanspro, og bruke denne på hver enkelt knapp.

Om det er ment å holde typografi separert fra knapper, bør det dokumenteres i storybook'en at man selv må sørge for rett font. Alternativt kan vi kanskje legge til slik at knapper by default bruker Source Sans Pro?

**Comment by erlendev** [comment]
Ja, det er nok best å holde typografi-komponentene separert fra knappene med tanke på at `<button>` ikke nødvendigvis er lagd med tanke på å ha `<span>` e.l. som children. Foreslår slik som du er inne på å bare legge inn font-family med Source Sans Pro i knapper-style-modulen, slik at man slipper å override dette selv.
