### ISSUE TITLE
Søkefelt

### ISSUE THREAD

**Issue by taniaholst** [navikt/aksel#1156]
## Beskriv forespørselen

Skulle gjerne hatt et Input-felt med forstørrelsesglass-ikon og placeholder, slik som det finnes i Figma.

## Hvilken funksjon vil dette har for bruker?

Tydeliggjøre av hva som er søkefelt vs hva som er et vanlig inputfelt.

## Eksempler/Tilleggsinformasjon 

Fra Figma
<img width="318" alt="Bilde av inputfelt med forstørrelsesglass ikon" src="https://user-images.githubusercontent.com/21334782/128175382-df57be3e-2a03-4525-9179-9d026faaaded.png">

**Comment by KenAJoh** [comment]
Har nå en WIP "SearchField" komponent ute, kan finnes her: https://navikt.github.io/Designsystemet/?path=/story/ds-react-form-search-field-intro--page
