### ISSUE TITLE
AriaLive-tag på <textarea> ved overskridelse av antall tegn

### ISSUE THREAD

**Issue by erlendev** [navikt/aksel#116]
Det har dukket opp et ønske om å legge på `aria-live="polite"` på `<textarea>` når brukeren har 10-0 tegn igjen, samt `aria-live="assertive"` når man har overskridet antall tegn.

**Comment by nutgaard** [comment]
any progress?

**Comment by erlendev** [comment]
Denne fikset jeg i høst en gang, lukker saken :)
