### ISSUE TITLE
Se på muligheten for å basere Grid-systemet på flexbox

### ISSUE THREAD

**Issue by erlendev** [navikt/aksel#125]

**Comment by thomasfl** [comment]
God idè. I [veiviser for sosialhjelp](https://tjenester.nav.no/veivisersosialhjelp) har vi laget en kombinasjon av gridsystem og panelbokser implementert i flex, så vi får denne jsx koden:

```html
<PanelRad>
    <Panel>Panel 1</Panel>
    <Panel>Panel 1</Panel>
    <Panel>Panel 1</Panel>
<PanelRad>
```

Det ligger en [pull request inne](https://github.com/navikt/nav-frontend-moduler/pull/34). Koden må forenkles og ryddes opp i før det er klart for å brukes på andre prosjekter

**Comment by nutgaard** [comment]
grid og flex er to forskjellige layout-systemer, hvorfor skal man blande de sammen? Om noe så kan man heller se på css-grid, som nå er relativt godt supportert. 

En annen ting man må holde i bakhode her er at gridet ligger som en del av nav-frontend-core så da bør det evt. tittes på å gjøre det bakoverkompatibelt. Noe jeg mistenker blir en relativt stor jobb, og noe som ikke vil gi spesielt stor verdi.

**Comment by frodehansen2** [comment]
Hvordan er gridsystemet brukt i dag? Anbefalingene er vel å ikke bruke det layout for hele sider, mer for deler av en side, og for optimalisering i mindre komponenter. Antar at grid er brukt en del til å sette opp hele sider?

**Comment by thomasfl** [comment]
@nutgaard Enig. Det er bedre å bruke css-grid enn css-flex. Hadde vært interessant å vite hvor mange prosent av brukere som har nettlesere som ikke støtter css grid layout. Selv om css grid er nytt, så har alle nye nettlesere støtte for det. Den største showstopperen er antagelig at IE9 ikke har støtte for det.

**Comment by nutgaard** [comment]
Grid for side-layout og flex innenfor avgrensede områder er vel anbefalingen ja.

Angående hvor mange som har browser som funker med css-grid så kan jeg prøve finne frem noe på Google analytics. Tror jeg fortsatt har tilgang der. 😛

**Comment by nutgaard** [comment]
| Browser | Prosent |
|----------|--------|
| Chrome | 35.68% |
| Safari | 28.54% |
| IE | 17.29% |
| Samsung Internet | 6.82% |
| Edge | 4.95% |
| Firefox | 4.51% |
| Opera | 0.80% |
| Android Webview | 0.61% |
| Safari (in-app) | 0.55% |
| Android Browser | 0.20% |

* Majoriteten av de som bruker chrome er på chrome@59 eller nyere, så disse er i orden.
* Er relativt mange som bruker safari@10 og safari@9 (36% av safari-brukerne).
* IE > 10 brukes av 99.2% av IE brukerne, så disse fungerer med prefix.

Sånn jeg ser det er det litt for mange som fortsatt ikke har støtte for css-grid (optimistiske tall ligger på rundt 25%). 

https://caniuse.com/#feat=css-grid
