### ISSUE TITLE
Styling av tekstinnhold for CMS-lignende løsninger

### ISSUE THREAD

**Issue by erlendev** [navikt/aksel#126]
Det har dukket opp et behov for å kunne style elementer som kommer fra en CMS-lignende løsning som enkle html-elementer uten klassenavn, som `<h1>`, `<h2>`, `<a>` og lignende.

Mulig løsning(?)
Lag en ny style-modul med en klasse som bare styler opp globale elementer innenfor den klassen med bruk av mixins fra de aktuelle style-modulene (lenker-style og typografi-style antageligvis).

En mulig utfordring med den løsningen er at flere typografi-elementer i noen tilfeller benytter seg av samme tag, som f.eks. Sidetittel vs. Innholdstittel, som begge er `<h1>`. 

Andre forslag / tanker?

**Comment by KenAJoh** [comment]
Lukker grunnet inaktivitet
