### ISSUE TITLE
Test av modal i StoryBook'en fungerer ikke med skjermleser.

### ISSUE THREAD

**Issue by DeamonDavid** [navikt/aksel#14]
Når man trykker på "Klikk for å åpne" test-modal i StoryBooken, får ikke skjermlesere det med seg.
Det ser ut som modalen åpnes, men at det ikke eksponeres for skjermleser.
Er dette en bug i modal-koden eller StoryBook'en, eller noe helt annet?
Testet med Chrome + JAWS 16 (NAV Skrivebord) og Safari + VoiceOver (iOS 10.3.2).

**Comment by nutgaard** [comment]
Eksemplene kjører innenfor en iframe, så det kan være med påvirke opplevelsen. 

Samme modal-implementasjon uten iframe-tull kan testes her; https://nutgaard.github.io/simple-modal-ex

Hvis du opplever samme problem der, så må vi ta en ekstra runde på modalene våre. :)

**Comment by DeamonDavid** [comment]
Ja, med den linken funka det. Men rart at akkurat den der ikke funker i StoryBooken.
Det meste andre jeg har sett på ser ut til å funke fint (Kun den der jeg har testa med Safari på iOS da).

**Comment by nutgaard** [comment]
Mistenker at det har noe med iframe'en å gjøre. Når modalen åpnes så mountes den på body-taggen til iframe'en ikke på body-taggen til hele siden. Så det er sikkert noe tull der som gjør at JAWS et.al. ikke får det med seg. Men vi bruker ikke iframes til daglig i våre løsninger, så om eksemplet jeg postet fungerer så kan vi være relativt trygge på at modalen fungerer som forventet. :)

**Comment by nutgaard** [comment]
Lukker denne, da testen utenom storybook var ok. Si ifra om det er noe mer krøll med modalen. Da kan vi evt. lage nytt issue, eller åpne denne igjen. :)
