### ISSUE TITLE
Label til skjemaelementer er bredere enn selve label-teksten

### ISSUE THREAD

**Issue by otenav** [navikt/aksel#15]
Label til skjemaelementer har display: block og tar derfor 100% bredde og labelen har ofte masse tomrom etter selve label-teksten. Siden label er klikkbar, gir dette noen uønskede effekter:
- En label for radiobutton/checkbox har cursor:pointer, noe som gjør at man kan se en pointer uten at man tilsynelatende har musen over radioknappen eller checkboksen.
- Om man tilsynelatende klikker på et tomt område, men egentlig klikker på labelen, kan man være uheldig å endre verdien på en radioknapp/checkox uten å få dette med seg.
- Om man klikker utenfor et skjemaelement, for eksempel om man vil ha fokus ut av en input, kan man komme til å klikke på det blanke området i labelen, noe som fører til at man setter fokus tilbake til input.

**Comment by nutgaard** [comment]
Takk for at du melder ifra. 
Jeg lurer på om vi kanskje har fått inn en fiks for dette allerede i det gamle repoet. Men kan dobbeltsjekke etter vi får gjort siste syncen. :)

**Comment by nutgaard** [comment]
Blir løst av #23 når den merges til master
