### ISSUE TITLE
Konvertere moduler til TypeScript

### ISSUE THREAD

**Issue by etse** [navikt/aksel#154]
Løpende arbeid, som kan startes på etter #153 er merget inn. Burde kanskje lage en oversikt over hvilke moduler som er konvertert, og hvilke som gjenstår så man ha en fremdriftsplan?

**Comment by nutgaard** [comment]
Lage issue for hver enkelt og teste ut milestone-funksjonaliteten i github? 
Eller hva tror folk?

**Comment by etse** [comment]
Kan være lurt, lettere å følge med på hva som skjer. Men hørtes veldig tungvindt ut å sette opp :)

**Comment by nutgaard** [comment]
Yeah, vi har vel 20-ish moduler som det må lages issues for. 
Milestone-biten etter det burde være  greit. ;)

**Comment by etse** [comment]
Har litt ledig tid, kan prøve å få lagt de til :)
