### ISSUE TITLE
Konvertere nav-frontend-ekspanderbartpanel til TS

### ISSUE THREAD

**Issue by etse** [navikt/aksel#159]

**Comment by kjarbr** [comment]
Vi har jobbet med å konvertere denne til typescript, og får følgende feilmelding når vi starter guideline-appen:
ERROR in ./packages/node_modules/nav-frontend-ekspanderbartpanel/src/index.tsx
Module parse failed: Unexpected token (10:7)
You may need an appropriate loader to handle this file type.
|  */
Typescript-loaderen feiler på helt grunnleggende ting. Bl.a på ordet "interface".
Noen som har en idé om hva dette kan skyldes?

Her er hele feilmeldingen:
ERROR in ./packages/node_modules/nav-frontend-ekspanderbartpanel/src/index.tsx
Module parse failed: Unexpected token (10:7)
You may need an appropriate loader to handle this file type.
|  */
| 
| export interface EkspanderbartpanelProps {
|     /**
|      * Skal komponenten være 'default' åpen
 @ ./packages/node_modules/nav-frontend-ekspanderbartpanel/_ekspanderbartpanel.sample.js 7:13-39
 @ ./packages/node_modules _[a-z]+\.sample\.js
 @ ./guideline-app/app/data/components/components.js
 @ ./guideline-app/app/data/index.js
 @ ./guideline-app/app/utils/routing/routes.utils.js
 @ ./guideline-app/app/utils/routing/routes.config.js
 @ ./guideline-app/app/utils/routing/routes.component.js
 @ ./guideline-app/app/ui/containers/app/App.js
 @ ./guideline-app/app/ui/app.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./guideline-app/app/ui/app.js

**Comment by Lillebo** [comment]
Fikset med #233
