### ISSUE TITLE
Når man klikker på radioknapper og checkbokser i modaler, settes midlertidig fokus til modal

### ISSUE THREAD

**Issue by otenav** [navikt/aksel#16]
Jeg har en modal med flere radioknapper/checkbokser, og hver gang jeg klikker en av radioknappene/checkboksene, så vises en oransje fokuskant på modalen et kort øyeblikk. Jeg forventet at fokus kun skal vises på den radioknappen jeg klikker, ikke på modalen.

Det samme skjer forøvrig når man klikker på en label for andre skjemaelementer.

**Comment by nutgaard** [comment]
Dette skjer ved `mousedown` og er default oppførsel av browsere. Tilsvarende oppførsel kan ses på kodesnutten under;
```html
<div tabindex="-1">
    <input type="radio" id="radio1" name="radio" value="1">
    <label for="radio1">Radio 1</label>
    <input type="radio" id="radio2" name="radio" value="1">
    <label for="radio2">Radio 2</label>
</div>
```
Fjerner man `tabindex` og kontinuerlig sjekker fokus-elementet mens man klikker på radioknappene ser man fortsatt samme oppførsel. E.g når `input`-elementer har fokus helt til `mousedown` da får `body`-fokus.

![image](https://user-images.githubusercontent.com/1413417/27329245-3fe0f050-55b5-11e7-94fa-6a0927c95db8.png)

Hvorvidt komponentene bør oppføre seg annerledes enn bare html kan diskuteres. Men jeg er nok av oppfatningen av de ikke bør gjøre det.

**Comment by erlendev** [comment]
Vi lukker denne saken, gjenåpne heller om vi ser behov for å legge inn fiks på dette i nav-frontend senere.
