### ISSUE TITLE
Størrelsen på radio-knapper og checkbox-er skal være 24px

### ISSUE THREAD

**Issue by erlendev** [navikt/aksel#194]
Idag er de 18px i height og width, men de skal visstnok være 24px.

Hvor mye vil dette ha å si for prosjektene der ute? Tas opp på frontend-forum.

**Comment by nutgaard** [comment]
Tok noen screenshots av en løsning som har en del radio/checkbokser, så vi har litt sammenligningsgrunnlag. 

## Med 18px størrelse: 
![image](https://user-images.githubusercontent.com/1413417/34760810-870574fc-f5e1-11e7-8c6a-f8e2afdb7352.png)
![image](https://user-images.githubusercontent.com/1413417/34760834-929d26ac-f5e1-11e7-8688-b76ae8e1d4f7.png)
![image](https://user-images.githubusercontent.com/1413417/34760839-99416a4a-f5e1-11e7-9128-59cc4229a871.png)


## Med 24px størrelse: 
![image](https://user-images.githubusercontent.com/1413417/34760745-520befce-f5e1-11e7-88e7-8c6c44fe2182.png)
![image](https://user-images.githubusercontent.com/1413417/34760761-5b032700-f5e1-11e7-93cd-9da6f4bb2394.png)
![image](https://user-images.githubusercontent.com/1413417/34760788-722410ca-f5e1-11e7-842a-b031d03fe855.png)

**Comment by erlendev** [comment]
Før vi implementerer det her må vi se på font-justeringer og avstander mellom checkbox og radio-knapper. Er det viktig nok å gjøre mtp. hvor mye jobb dette potensielt fører til ute i prosjektene? @sergiohaisch

**Comment by sergiohaisch** [comment]
Det er nok det ja. Er dette noe vi kan ta opp i Frontend Forum og designhjørne, høre med designere og frontendere, se om de har noen konkrete innspill?


------------------------------------
Med vennlig hilsen

Sergio Haisch
Lead Visuell Designer // Ansvarlig for designsystemet
Kontor for brukerdialog  //  Forvaltningsseksjonen
NAV IT //  Arbeids- og velferdsdirektoratet
: 41 26 23 39
www.nav.no<http://www.nav.no/>





On 10 Jan 2018, at 10:44, Erlend Vige <notifications@github.com<mailto:notifications@github.com>> wrote:


Før vi implementerer det her må vi se på font-justeringer og avstander mellom checkbox og radio-knapper. Er det viktig nok å gjøre mtp. hvor mye jobb dette potensielt fører til ute i prosjektene? @sergiohaisch<https://github.com/sergiohaisch>

**Comment by erlendev** [comment]
Ta gjerne opp i designhjørnet også @sergiohaisch 👍  min kommentar var oppsummering av tilbakemeldingene fra frontend-forumet.
