### ISSUE TITLE
Property name legges ikke til som input attributt

### ISSUE THREAD

**Issue by otenav** [navikt/aksel#195]
name må legges til <input>, slik at det virker med form submit

https://github.com/navikt/nav-frontend-moduler/blob/56986b8de084e1ee79e65ceecb4dd910c195b065/packages/node_modules/nav-frontend-skjema/src/input.js#L21

**Comment by nutgaard** [comment]
`...other` blir satt på input-element, så om man sender med `name` så burde det havne i DOMen. 
:/

**Comment by otenav** [comment]
name trekkes ut fra props som egen constant så den vil ikke være en del av others

**Comment by nutgaard** [comment]
oops, ja. Så ikke den. Tror det skal være løst i #179, men kanskje greit å få fikset så fort som mulig egentlig.
