### ISSUE TITLE
Snakkeboble header

### ISSUE THREAD

**Issue by nutgaard** [navikt/aksel#198]
Det er ønskelig med litt mer informasjon i "header" til snakkeboble-komponent (i dette tilfellet avsender), og litt mer spacing mellom "header" og innhold.

Forslår en endring der `.snakkeboble-panel__dato` også får `blokk-xs`. 

Ex.: 
![image](https://user-images.githubusercontent.com/1413417/35445172-0d56fd24-02b1-11e8-8421-c75e83f11951.png)

**Comment by Lillebo** [comment]
Hm, får feilmelding på Snakkeboble-sample når jeg kjører opp lokalt:

```
Warning: Failed prop type: The prop `topp` is marked as required in `Snakkeboble`, but its value is `undefined`.
    in Snakkeboble (created by Sample)
```

Som forsåvidt gir mening utifra sample og propTypes/interface, men litt rart at denne feilen ikke slår ut i prod. Kanskje vi bare skal gjøre både `topp` og `dato` optional her, og hoppe over rendering av topp hvis ingen av dem er gitt?

**Comment by nutgaard** [comment]
https://github.com/navikt/nav-frontend-moduler/pull/200/files#diff-5d5973fb965096fc308f1e6cb54356abR54

Komponenten støtter både `topp` og `dato` per i dag. Gjorde det slik at den ikke skulle brekke ting for folk. Men la til en liten `@Deprecated` på `dato` slik at folk skal ha tid til å fikse opp i ting før vi fjerner den.

Ville heller endret på eksemplet slik at det bruker `topp` istedet. Men jeg burde kanskje ha lukket dette isset, for dette er egentlig merget inn via #200
