### ISSUE TITLE
Endre innholdet i <title>-elementet i Guideline-appen

### ISSUE THREAD

**Issue by DeamonDavid** [navikt/aksel#208]
I guideline-appen, endres ikke <title>-elementet seg etter hvilke "side" som er valgt.
Dette gjør det utfordrende å vite hvor man er når en bruker skjermleser, uten å sjekke det manuelt.
I tillegg, om man f.eks deler link til et element på Facebook, blir tittelen på linken bare "Designsystemet", og man må gå inn for å se hva det linkes til.
https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-title.html

**Comment by erlendev** [comment]
Løses trolig relativt enkelt med bruk av DocumentTitle.

https://github.com/gaearon/react-document-title
