### ISSUE TITLE
Legge inn prettier-formattering på precommit

### ISSUE THREAD

**Issue by erlendev** [navikt/aksel#257]

**Comment by unorsk** [comment]
Om det er åpent til diskusjon:
Kan vi ha tslint/eslint koblet til circle ci / github pull requests på en sånn måte at det blir umulig å merge pull-request før alle warnings er fikset (og det er ikke et stor jobb å kjøre `tslint --fix` selv, kunne også ha det i package.json/scripts)?  Forresten, det gjelder tests også.

*Edit*: Har nettopp merket at vi har tilsvarende pull-request [tslint](https://github.com/navikt/nav-frontend-moduler/pull/256/)

**Comment by KenAJoh** [comment]
Implemented by #824
