### ISSUE TITLE
Radiopanelgruppen lar deg ikke endre valg

### ISSUE THREAD

**Issue by solhell** [navikt/aksel#274]
https://navikt.github.io/nav-frontend-moduler/#/components/radiopanelgruppe
Her er det ikke mulig å endre valget.
Testet i Chrome 66 på Mac.

**Comment by nutgaard** [comment]
Hei, og takk for at du rapporterte dette inn. 

Her var det litt krøll i eksempel-generatoren, men komponenten i seg selv fungerte som forventet.

PR #277 fikser opp i eksempel-generatoren slik at eksemplet nå skal være interaktivt.
Endringene vil ikke være synlig på nettsiden før PRen blir godkjent. Men det burde kunne skje relativt raskt.
