### ISSUE TITLE
Input radio og checkbox bør ha spesifikk kobling med label

### ISSUE THREAD

**Issue by solhell** [navikt/aksel#275]
Per nå er det på radio og checkbox bare brukt implisitt kobling med label på formen
<label><input type="radio">Beskrivelse</label>

Enkelte eldre skjermlesere takler ikke implisitte koblinger, så dette bør suppleres med matchende for- og id-attributt på formen
<label for="id"><input type="radio id="id">Beskrivelse</label>

**Comment by nutgaard** [comment]
Hei, og takk for at du rapporterer feil og mangler. 👍 Det setter vi utrolig stor pris på. 

De ordinære radio/checkboxene hadde allerede en eksplisitt kobling mellom label og input. Men panel-gruppe komponentene manglet dette. 

PR #276 legger til for/id-attributtene for radio-panel-gruppe og checkboks-panel-gruppe.
