### ISSUE TITLE
Forbedre SkjemaGruppe-eksempel og lage eksempel på Fieldset m/Legend

### ISSUE THREAD

**Issue by solhell** [navikt/aksel#279]
https://navikt.github.io/nav-frontend-moduler/#/components/skjemagruppe

Her skulle spørsmålet vært `legend` for et `fieldset` som omfatter svaralternativene.

**Comment by erlendev** [comment]
Sånn jeg har forstått det skal `<fieldset>` og `<legend>` brukes i `radio` og `checkbox`-tilfeller, men ikke nødvendigvis ved gruppering av andre inputs som vanlig type=text eller textarea-elementer.

Forøvrig har vi en egen `Fieldset`-komponent som tar inn `legend` her (som vi bør få inn et eksempel på):
https://github.com/navikt/nav-frontend-moduler/blob/master/packages/node_modules/nav-frontend-skjema/src/fieldset.tsx

**Comment by solhell** [comment]
Helt enig, men i denne komponenten er det altså som følger:
1. en gruppe `checkbox`, hvor det ofte trengs `fieldset` og `legend`, og definitivt med disse eksempeltekstene
2. med gitte eksempeltekster skulle det vært `radio`, som praktisk talt alltid trenger `fieldset` og `legend`
3. det er ikke `fieldset` og `legend` i komponenten

Forøvrig: Eksempel på situasjon hvor det er nødvendig også ved andre typer input, er dersom man har separate adresser f.eks. for faktura, post, besøk o.l. Da vil det være flere felt med samme beskrivelse, og `fieldset`/`legend` er nødvendig for å skille dem.

**Comment by erlendev** [comment]
Ser at eksemplet er litt uheldig. Renamet issue'n - dette er egentlig ikke et problem med komponenten i seg selv, men med eksemplet som vises på siden.

**Comment by Lillebo** [comment]
Ser at det også er noen småfeil på `for`- og `id/name`-attributter ellers også. Trenger en gjennomgang.
