### ISSUE TITLE
For svak kontrast på avkrysningsboks

### ISSUE THREAD

**Issue by solhell** [navikt/aksel#280]
https://navikt.github.io/nav-frontend-moduler/#/components/bekreftcheckbokspanel

Kontrasten mellom rammen på avkrysningsboksen og bakgrunnen er nede i 1.5:1 (når ikke valgt). Anbefaler at dere følger WCAG 2.1 kriterie 1.4.11 og i hvert fall får den opp på 3.0:1.

Tilsvarende for https://navikt.github.io/nav-frontend-moduler/#/components/checkbokspanelgruppe, her er kontrasten på 1.8:1.

**Comment by erlendev** [comment]
@sergiohaisch @karinaldw Noe dere kan se nærmere på?

**Comment by Lillebo** [comment]
Kontrast på `Checkbokspanelgruppe` blir fikset med #251
