### ISSUE TITLE
Kontrastforhold - Farger

### ISSUE THREAD

**Issue by StaleKjone** [navikt/aksel#285]
Det er en del som tyder på at kontrastverdiene på fargene i Designsystemet må justeres noen steder. Vedlagt ligger en oversikt over fargene med justert kontrastverdi fra www.contrastchecker.com. Sjekk gjerne en gang til om de stemmer underveis i oppdateringen.

[Designsystemet-kontrastforhold.pptx](https://github.com/navikt/nav-frontend-moduler/files/2044714/Designsystemet-kontrastforhold.pptx)

**Comment by nutgaard** [comment]
Kan automatiseres slik at vi unngår feil ratio i fremtiden. 

Ressurser for å kalkulere ratio: 
https://www.w3.org/TR/2008/REC-WCAG20-20081211/#contrast-ratiodef
https://www.w3.org/TR/2008/REC-WCAG20-20081211/#relativeluminancedef

**Comment by Lillebo** [comment]
Fikset med #286
