### ISSUE TITLE
Verktøy for testing av universell utforming

### ISSUE THREAD

**Issue by Lillebo** [navikt/aksel#292]
Diskusjon, erfaringer og anbefalinger ønskes 🙂

**Comment by DeamonDavid** [comment]
Har hørt noen har snakket litt om SortSite. Her har dere noen tanker (ikke fra meg): http://eksempelsamling.medialt.no/automatisert-tilgjengelighetstesting-sortsite/

For de på Facebook, kan også kommentartråden være verdt å ta en titt på: https://www.facebook.com/groups/iktuu/permalink/561045760761332/

**Comment by orhels** [comment]
Team-søknad har tatt i bruk pa11y (https://github.com/pa11y/pa11y) for å teste UU. Per tid har vi bare enkle tester som går inn på hver side i appen og lager en rapport, men skal være mulig å gjøre mer kompliserte tester.

**Comment by StaleKjone** [comment]
Bruker SortSite og (av og til) Total Validator Pro til validering av nettsider og tjenester. Fungerer rimelig greit for teknisk. En del "falske positiver". Ellers er utstyrspakken min omtrent som det her med utvidelser og alt:

### Validering av kode mot W3C-standarder m.m:
### SortSite 
Godt verktøy for validering av grensesnittkode opp mot W3C-standarder som WCAG 2.0/2.1, HTML5, CSS3, etc. Gir en god oversikt sammen med en god beskrivelse av hva som er feil, hvor feilen er og hvordan den kan fikses. 

SortSite er et for verktøy for testing av nettsteder som brukes av oss i NAV, men har også referanser i USA som føderale byråer, Fortune 100-selskaper og uavhengige konsulentfirmaer. Verktøyet er tilgjengelig som et skrivebordsprogram for Mac eller Windows, og er også tilgjengelig som et webprogram. NAV IT bruker hovedsakelig skrivebordsprogrammet.
		 
Plattformer: Macintosh og Windows Bruk: Innvendig og utvendig brannmur, inkludert intranett, nettsider og utviklingsmiljøer. Hver side er sjekket mot mer enn 1200 standardbaserte kontrollpunkter.
		 
Sjekkpunkter
Universell utforming av IKT - Kontrollerer WCAG 2.0 og Seksjon 508 retningslinjer mot mange filtyper: finn blinkende GIF, untagged PDF-filer
Broken Links - ser etter ødelagte koblinger og stavefeil
Kompatibilitet - ser etter HTML, skript og bildeformater som ikke fungerer i vanlige nettlesere
Søkemotoroptimalisering - sjekker retningslinjene for Google og Bing
Personvern - kontrollerer etterlevelse av EUs og USAs lov (usikker på hvor godt dette egentlig er med tanke på GDPR)
Webstandarder - validere HTML og CSS
Brukervennlighet - sjekk mot Usability.gov retningslinjer
[SortSite dokumentasjon](http://www.powermapper.com/products/sortsite/rules/accwcag2/) (oversikt over alle regler)
 
Rett og slett et godt verktøy. Pris ca NOK 8-10.000,- per lisens

### SiteImprove 
Bruk ikke denne per i dag pga manglende lisens. Godt verktøy som gir deg en lettfattelig og god oversikt over problemer og forbedringsområder. Som f.eks. dårlig kodekvalitet og kvalitetsfeil som brutte lenker og stavefeil, kontrastforhold som er for dårlig, m.m. Verktøy tester opp mot W3Cs standarder som f.eks. HTML5 og WCAG 2.0/2.1 og man kan filtrere funnene på roller (utvikler, redaktør, etc). God beskrivelse for hva som er feil og hvordan det kan fikses.

### Total ValidatorTool Pro 
Har vært ett av de bedre verktøyet til validering av kildekode og støtte for universell utforming. Se http://www.totalvalidator.com/. 
	Pro-versjonen til kr 250,-

### Chrome DevTools (F12)
Chrome DevTools er et sett med webutviklerverktøy som er bygget direkte inn i Google Chrome-nettleseren. DevTools kan hjelpe deg med å redigere/manipulere en hvilken som helst nettside/tjeneste og diagnostisere problemer raskt. Kan bygges ut med diverse andre utvidelser. Gratis

### Audits/Lighthouse (AXE) 
er åpen kildekode og er et automatisert verktøy for å forbedre kvaliteten på nettsidene, både åpne og bak innlogging. Du kan kjøre verktøyet mot en hvilken som helst nettside. Den har evalueringsmuligheter for ytelse, tilgjengelighet/uu, progressive webapps, beste praksis, søkemotoroptimalisering for både mobile enheter og desktop.

Du kan kjøre Lighthouse i Chrome DevTools, fra kommandolinjen, eller som en nodemodul. Du gir Lighthouse en URL for å revidere, den kjører en del sjekker mot siden, og så genererer den en rapport som inneholder hvor godt siden gjorde det. Derfra bruker du de revisjonene som indikatorer på hvordan du kan forbedre siden. Hvert revisjon har en referansedokument som forklarer hvorfor revisjonen er viktig, samt hvordan det skal løses. Gratis
		
### Web Developer
Toolbar med et hav av muligheter til å manipulere og konfigurere løsningen. Gratis

### Visual Aria
Viser ARIA som brukes i webteknologi, inkludert live region og widget roles, riktig nesting og fokushåndtering. Gratis.

### SiteImprove Accessibility Checker
https://chrome.google.com/webstore/detail/siteimprove-accessibility/efcfolpjihicnikpmhnmphjhhpiclljc
Bra verktøy for å vurdere en nettside opp mot WCAG. Gratis.

### WAVE - https://wave.webaim.org/
Evaluerer tilgjengelighet direkte i en nettside. Veldig visuell. Gratis.

### AXE Coconut fra Deque (kjøpt opp av Google)
Tilgjengelighetstesting i Chrome Developer Tools. Gratis.

### Adobe Acrobat DC 
Validering av PDF-skjema opp mot W3C standarder som WCAG 2.0/2.1 (Verktøy>Tilgjengelighet>Tilgjengelighetskontroll eller Full kontroll. NAV har lisenser på dette. Mer info:https://helpx.adobe.com/no/acrobat/user-guide.html?topic=/no/no/acrobat/morehelp/accessibility_tags_and_reflow.ug.js 

Sjekker også kontrastforhold innad i en PDF (Verktøy>Tilgjengelighet>Tilgjengelighetskontroll eller Full kontroll. NAV har lisenser på dette. Mer info:https://helpx.adobe.com/no/acrobat/user-guide.html?topic=/no/no/acrobat/morehelp/accessibility_tags_and_reflow.ug.js 

### **Allround-verktøy**
### Funkify Simulator
Simulerer koginsjonsproblemer, dysleksi, fargeblindhet, ADHD, sterkt lys, m.m. God! Bør vurdere abonnement!
Se https://www.funkify.org/
		
### **Lese- og skrivevansker**
### Dyslexia Formatter
Gjør det enklere å tilegne seg informasjon og bruke nettbaserte tjenester for folk med dysleksi. Gratis.

### **Kontrastforhold**
Bør vurdere å bygge en selv kontrastsjekker inn i Designsystemet.

### http://contrastchecker.com/ 
Her kan du legge inn fargekodene dine og få et konkret svar om kontrastforholdet er i tråd med WCAG-kravene. Du kan også se gråtoner som fargeblind (arkfaner øverst til høyre). Gratis
Se også https://webaim.org/resources/contrastchecker/ og http://accessible-colors.com/. Gratis. 

### **Mobil- og nettleserkompatibilitet (ikke lisens på disse for min del per i dag)**
### BrowserStack 
Instant access to 1200+ real mobile devices and browsers. Ship mobile apps and websites that work for everyone, every time… Lisenser kjøpt inn. NOK xx,. per lisens.

### Sauce Labs 
Tester om løsningen fungerer på kjente nettlesere, operativsystem og enheter. Lisenser på gang og team som implementerer dette i byggeprosessen?

### NAV SanseLab
Ellers har Team universell utforming av IKT opprettet NAV SanseLab på rom 5006 i Sannergata 2. Der står det diverse informasjon om universell utforming av IKT og ikke minst en god del utstyr for å selv kunne teste ut hvordan diverse funksjonsnedsettelser fungerer i praksis.

**Comment by dervism** [comment]
I FO har vi laget NAV-Ally - en lignende løsning som Pa11y. Det er flere forskjeller dog. NAV-Ally bruker Axe (samme valideringsmotor som i Chrome) og konfigureres via en enkel Yaml-fil. Vi lagde NAV-Ally fordi ingen av verktøyene som fantes den gang løste våre behov.

NAV-Ally er tilgjengelig både som NPM-pakke og som Docker-image som kan integreres i våre bygg-servere. Jeg har presentert NAV-Ally for blant annet Norsk Regnesentral og flere ganger internt i NAV. Dersom noen ønsker å teste det ut, eller høre hvordan den funker så er det bare å ta kontakt.

Her er prosjektet:
https://github.com/navikt/nav-ally

Docker-dokumentasjon med info om hvordan du kan lage Jenkins-stage med UU-test.
https://cloud.docker.com/u/navikt/repository/docker/navikt/nav-ally

NAV-Ally støtter UU-tester mot direkte lenker og tester med actions. Følgende er støttet: click, keyboard (simulere tastetrykk), type (skrive tekst), find (med xpath, className, id, link text, name), select, wait, pause/sleep, switch frame. Begge disse kan settes i en Yaml-fil. 
Dokumentasjon med eksempler her: https://github.com/navikt/nav-ally/blob/master/documentation.md

I FO deployer vi ofte mocker til Heroku og setter opp våre UU-tester til å gå mot disse instansene.
