### ISSUE TITLE
Ekspanderbartpanel-heading midtstilles når teksten går over flere linjer

### ISSUE THREAD

**Issue by PerOlavM** [navikt/aksel#293]
Typisk på mobil (smale skjermer).
Ser ikke bra ut hvis man har flere paneler under hverandre.

**Comment by erlendev** [comment]
Kan du legge ved et skjermbilde her @PerOlavM?

**Comment by PerOlavM** [comment]
![screen shot 2018-05-31 at 11 40 16](https://user-images.githubusercontent.com/35491554/40775121-9219f0b6-64c7-11e8-9a97-58ec1ca201e2.png)
https://tjenester.nav.no/veiviserarbeidsgiver/tilrettelegge

**Comment by erlendev** [comment]
Hm, merkelig oppførsel på mobil her ja. For meg ser det ut som det midtstilles når teksten går over flere linjer på mobil. Er dette by design @sergiohaisch?

**Comment by nutgaard** [comment]
Undersøkte raskt i chrome nå, og ser ut som stylingen `text-align: center` er aktiv på elementet med klasse `.ekspanderbartPanel__heading`. Dette er en arvet property fra chrome's user agent stylesheet på alle `button`-elementer. `text-align: left` vil løse dette problemet

**Comment by sergiohaisch** [comment]
Er dette fikset? @PerOlavM @erlendev

**Comment by erlendev** [comment]
Fikset nå @sergiohaisch ☝️
