### ISSUE TITLE
Endre aria-labelled-by i BekreftCheckboksPanel til aria-described-by

### ISSUE THREAD

**Issue by Lillebo** [navikt/aksel#294]
`aria-labelled-by` erstatter tekst-verdi i `<label>`. Sjekk med David først.

**Comment by Lillebo** [comment]
Etter å ha testet med @deamondavid kan det virke som at det beste hadde vært å unngå både `aria-describedby` og `aria-labelledby` på denne. Har du noen tanker om det @karinaldw?

**Comment by DeamonDavid** [comment]
Den enkle forklaringa er at det ikke gir noe ekstra verdi å ha det på, at least for skjermlesere.

**Comment by Lillebo** [comment]
Yup 👍

**Comment by karinaldw** [comment]
Kan hende at det fungerer med bare aria-expandet og aria-controls. Fant et interessant eksempel på nettet, men de bruker da bare meny-knappen, og ikke noe x.. Kan det uten videre overføres til vår knapp?

http://www.a11ymatters.com/pattern/mobile-nav/#using-aria-attributes-for-the-toggle-element @Lillebo @DeamonDavid

**Comment by Lillebo** [comment]
Mistenker den kommentaren hører hjemme på #295 @karinaldw 🙂

**Comment by karinaldw** [comment]
det gjør den, sorry, blandet litt :) @Lillebo

**Comment by karinaldw** [comment]
Så lenge labelen til selve sjekkboksen er mer enn bare "ja", så burde det vel være ok... Litt usikker her, jeg og. @DeamonDavid , hvordan er det løst andre plasser?

**Comment by DeamonDavid** [comment]
Oy, hadde glemt denne :package: Det er jo bare en vanlig checkbox, og burde dertil ha labelen den hører til. Det være seg "Jeg har lest og godtar vilkårene".

**Comment by Lillebo** [comment]
Enig 👍 Legger ut en fiks på dette snart.
