### ISSUE TITLE
Utbedre UU på Guideline-meny

### ISSUE THREAD

**Issue by Lillebo** [navikt/aksel#295]
- Wrappe meny og `mobileMenuToggleButton` i `<nav>`
- `mobileMenuToggleButton` bør få noe ala. `aria-controls` som peker på navigasjonen (bør undersøkes mer)
- Menypunkter som har undermenypunkter bør få ~`aria-haspopup`~ og `aria-expanded`
- Mobilmeny bør lukkes automatisk ved valg av nytt menupunkt

**Comment by karinaldw** [comment]
Sjekket du med David at det var riktig at det leses opp "Åpne meny, knapp, navigering, landmerke" når man har åpnet menyen og egentlig bare ser lukk-knappen, @Lillebo ?

**Comment by Lillebo** [comment]
Hm, nei den har vi ikke testet. Lurer på hva som er best å gjøre her. Den åpne-knappen bør kanskje skjules når menyen åpnes, samtidig som vi setter fokus på lukk-knappen? Eller kanskje språket i åpne-knappen bare kan endres til "Vis eller skjul meny", ettersom den egentlig fungerer som en toggle?

**Comment by karinaldw** [comment]
Legger inn på riktig issue nå, ;)

Fant et interessant eksempel på nettet, men de bruker da bare meny-knappen, og ikke noe x.. Kan det uten videre overføres til vår knapp?

http://www.a11ymatters.com/pattern/mobile-nav/#using-aria-attributes-for-the-toggle-element @Lillebo @DeamonDavid
