### ISSUE TITLE
Splitte nav-frontend-skjema/textarea

### ISSUE THREAD

**Issue by jan-berge-ommedal** [navikt/aksel#3]
Lage separate komponenter for controlled og uncontrolled textareas.

Fra http://stash.devillo.no/projects/NAVFRONT/repos/nav-frontend-moduler/pull-requests/117/overview:

Utgaard, Nicklas
Skulle vi sett på å få splittet denne fila i to? Per i dag støttes både controlled og uncontrolled, men tror det skal være mulig å få til ett bedre skille mellom disse.
Evt. finne ut hvorfor noen har behov for uncontrolled, Juel, Ragnhild har vel vært med å legge inn noe av det. Så kanskje det er noen behov derifra?

Juel, Ragnhild
For nå så har vi kun behov for controlled. Ser absolutt at det kunne ha vært en fordel å splitte det opp i to, synes det er vanskelig å skulle kunne håndtere begge og unngå at oppdatering av tilstand blir gjort dobbelt.

Ommedal, Jan Berge
Utgaard, Nicklas Juel, Ragnhild Er det ok å merge denne PRen, eller ønsker dere at jeg splitter dette nå?
Finnes det en teknisk gjeld-liste man kunne ha satt dette på?

Utgaard, Nicklas
Tenker vi kan merge denne nå, så kan du lage ett issue på https://github.com/navikt/nav-frontend-moduler Vi jobber med å flytte all forvaltning av rammeverket over til github. Så derfor er det sikkert greiest å ta det der. :)

**Comment by nutgaard** [comment]
Denne blir løst når originmaster-branchen kommer inn

**Comment by nutgaard** [comment]
Blir løst av #23 når den merges til master
