### ISSUE TITLE
ToggleGruppe-komponent med to <ToggleKnapp /> trigger ikke checked-attributt ved første klikk

### ISSUE THREAD

**Issue by erlendev** [navikt/aksel#30]
Hvordan reprodusere:
- Gå inn på storybook (https://navikt.github.io/nav-frontend-moduler/?selectedKind=Toggle)
- På øverste toggle, klikk på "Knapp 2"
- Kun fokus er nå trigget, og checked trigges ikke på ToggleKnapp som nå har fått fokus, før man klikker en gang til. 

Testet kjapt checked vs defaultChecked, ser ikke ut til å være relatert til dette. Samme behaviour skjer med defaultChecked og to knapper. 

Reprodusert i Chrome, Version 59.0.3071.115 (Official Build) (64-bit), macOS Sierra.

**Comment by nutgaard** [comment]
De to nederste toggle-gruppene fungerer som normalt, så mistanken min var at dette hadde noe med eksemplet å gjøre fremfor komponentene. 

Renskrev `stories.js` slik at den bedre reflekterer hvordan kompontene ville blitt brukt, og da fungerer alle toggle-gruppene som forventet. Legger opp en PR #33 på det nå, så kan du avgjøre om noe mer bør gjøres.
