### ISSUE TITLE
Utbedre overskrift-hierarki/oppsett på Guideline-siden

### ISSUE THREAD

**Issue by Lillebo** [navikt/aksel#302]
Litt rar bruk av `h4` og `h2` noen steder

**Comment by karinaldw** [comment]
På fargesiden: må fargene være kodet som overskrifter? Blir fortsatt litt feil her, hopper fra h1 til h4. Mens "interaksjonsfarger" og "tilleggsfarger" ikke er kodet som overskrift, selv om de er overskrifter. Kan du se på den siden igjen? :)

**Comment by karinaldw** [comment]
Og på http://archivedworks.com/dev/nav/guideline/#/how-we-write: overskriftene på nivå 3 er ibland h-er, ibland ikke. Er det mulig å ha det kodet som h3, men likevel ikke ha noe linjeskift før teksten som kommer etter? Hvis ikke, så er det bedre hvis det er h3 med linjeskift enn at det ikke er kodet med h.

**Comment by Lillebo** [comment]
Oppdatert: 
- http://archivedworks.com/dev/nav/guideline/#/styling/farger
- http://archivedworks.com/dev/nav/guideline/#/how-we-write

@karinaldw

**Comment by karinaldw** [comment]
på fargesiden hopper vi fortsatt over et overskriftsnivå fra "Fargekontrast mellom tekst og bakgrunn" til de enkelte fargene (h2-h4). Men det er nok ikke direkte krise, og så har fargene samme h-nivå som ikke er så dumt (hvis de nå skal være overskrifter) @Lillebo

**Comment by Lillebo** [comment]
Ja, var litt usikker på hva som var best å gjøre her. Tenker det kanskje er greit at alle fargene har samme h-nivå ja. Kan høre med David hva han syns.
