### ISSUE TITLE
Ser ut som modal ikke funker som den skal med skjermleser

### ISSUE THREAD

**Issue by DeamonDavid** [navikt/aksel#305]
Når jeg åpner modal-eksempelet i guide-line appen, eksponeres det som er bak for skjermleser. Skal det det?

Fortsatt funker @nutgaard sitt eksempel som det skal, https://www.utgaard.xyz/simple-modal-ex/

**Comment by nutgaard** [comment]
Mistenker at dette har noe med eksemplet å gjøre, og ikke selve modulen. Må dobbeltsjekke om `setAppElement` blir satt der.

**Comment by Lillebo** [comment]
Er denne fortsatt aktuell @DeamonDavid ?
