### ISSUE TITLE
Feil i checked-state Radiopanel/checkbokspanel på iphone/ipad

### ISSUE THREAD

**Issue by Oslove** [navikt/aksel#311]
Når radioknapp eller checkboks blir avkrysset på iphone/ipad Safari så blir ikke fargen på input-boksen mørk blå slik den blir på andre enheter/os. Ser ut som at det er hover-state som blir vist?
Når man klikker utenfor panelet så får den riktig state. 
Det fungerer som det skal på Android. 

Brukt her:
https://tjenester.nav.no/jobbsokerkompetanse/

**Comment by Lillebo** [comment]
Hm, har du siste versjon av `nav-frontend-skjema` og `nav-frontend-skjema-style`? Lurer på om ikke dette ble fikset med #251. Her er en forhåndsvisning av hvordan disse komponentene blir med de siste oppdateringene: http://archivedworks.com/dev/nav/radios-checkbokser/

**Comment by Oslove** [comment]
@Lillebo Det hjalp visst å oppdatere skjema og skjema-style. Takk, da er alt i orden!
