### ISSUE TITLE
Fjerne transition ved responsivitet i stegindikator

### ISSUE THREAD

**Issue by nemanjaaks** [navikt/aksel#323]
Opplever en issue med at ved bruk av 
`<Stegindikator
                    steg={ indikatorsteg }
                    autoResponsiv={true}
                    visLabel={false}
                    kompakt={false}
                    aktivtSteg={hentIndeksForPath(currentPath)}
                />`

så forekommer det en animasjon hver gang man trykker på neste på liten skjerm. Det ser ut som indikatoren transitioner fra originalstørrelse til å være kompakt. 

En rask titt på koden viser at det kan ha noe med at 
 `&__steg-num {
...
    **transition: all linear 100ms;**
    background: white;
  }`

Bør denne kanskje fjernes?

**Comment by Lillebo** [comment]
Hm, finnes det en link til løsningen hvor jeg kan se problemet? Eller kunne du laget en liten videosnutt av det? Hvordan navigerer brukeren mellom stegene hos dere? Er det en ny sidelast for hver gang? 

Den transition-effekten er ikke så viktig, så vi kan sikkert fjerne den hvis den er problematisk - men har litt lyst å se først 🙂

**Comment by nemanjaaks** [comment]
![stegindikatorissue 1](https://user-images.githubusercontent.com/3842406/41654611-4dfaabd2-748a-11e8-9a4e-ca7bf5d2d3c0.gif)
Prøvde med en video til en gif her - tror man kan se den overgangen jeg snakka om. :)
