### ISSUE TITLE
Flere komponenter mangler eksplisitt font-stil

### ISSUE THREAD

**Issue by Lillebo** [navikt/aksel#324]
- Select
- Input
- Textarea
- Snakkeboble (`snakkeboble-panel__tekst`)
- Stegindikator (`stegindikator__steg-num`, `stegindikator__steg-label`)
- Tabs (`nav-frontend-tabs__tab-label`)
- Toggle (`toggle__label`)

Mens andre (`Checkbokspanel` osv.) setter dette eksplisitt. Bør dette utbedres slik at det gjøres likt i komponentene, eller holder det å be konsumentene om å laste inn `nav-frontend-core` og `nav-frontend-typografi` selv (som nevnt i #272) og la disse stilene bli arvet fra rot?

@nutgaard @erlendev @otenav

**Comment by nutgaard** [comment]
Tror en kombinasjon løser problemet best. 
Folk bør laste inn `nav-frontend-core` og `nav-frontend-typografi-style` selv for å få alle hjelpe-klassene og laste inn font-filene.

For  `Checkbokspanel` tenker jeg at man bruker `typo-normal` klassen eller at `inputPanel` bruker `typo-normal` som en mixin. Viktig at det brukes `@import (reference)` når typografi lastes inn her, slik at vi ikke laster den flere ganger enn nødvendig. 

Hvis `reference` ikke blir brukt så vil man få font-filene og all typografi-stylingen flere ganger når man bygger applikasjonen sin.
