### ISSUE TITLE
Lenkepanel og Ekspanderbartpanel har feil blåfarge på hover

### ISSUE THREAD

**Issue by Lillebo** [navikt/aksel#329]

**Comment by Lillebo** [comment]
@winsvold Hm, var det meningen å lukke denne?

**Comment by winsvold** [comment]
I alle dager, nope ;-)

Skulle skrive et spørsmål, men må har trykket i blinde.

Hvilken farge er det tenkt at den skal få? Designerene på teamet vårt ønsket seg nemlig et ekspanderbart panel uten fargeendring ved hover.

**Comment by Lillebo** [comment]
Aha 👍 

Den korrekte hover-fargen skal være navBlå (#0067C5). Alle klikkbare overskrifter/titler skal nok ha denne stilen, så jeg tror dessverre designerne deres må leve med det 🙂

**Comment by winsvold** [comment]
Mm, dette blir kanskje litt anderledes. Det er i bruk med ekspanderbartpanel-base og masse JSX-elementer som children i hodet.

![image](https://user-images.githubusercontent.com/29202094/42022538-da00bca0-7abd-11e8-84b9-a63e0f97e5c8.png)

**Comment by Lillebo** [comment]
Aha, skjønner. 

Hm, tror nok jeg likevel ville hatt korrekt hover-stil på familie-navnet der ved hover. Den øvrige teksten (som fødselsnummer osv under navnet, etikettene osv) trenger ikke noe slik stil. Antar klikkflaten går over hele innholdet, og panelet ekspanderes/kollapses normalt uavhengig om jeg klikker på etikettene eller tittelen/navnet?

**Comment by winsvold** [comment]
Hele flaten er klikkbar ja. Pinger på designeren vår, så kan hun se på dette.
