### ISSUE TITLE
Finnes det bare NodeJS/React komponenter?

### ISSUE THREAD

**Issue by polterguy** [navikt/aksel#331]
Finnes det ikke noen rene CSS muligheter, for å inkludere dette i andre typer prosjekter?

Slik som jeg har forstått dette, er meningen at dette skal standardisere utvikling for det offentlige. Betyr det at all utvikling av offentlig programvare må enten gjøres i React/NodeJS, eller er dette bare design guidelines, altså at man kan lage egne ports av dette ...?

**Comment by eirslett** [comment]
Har du prøvd å bruke pakken `<komponentnavn>-style` og hente ut CSS derfra? Og bare replikere DOM-strukturen som React-komponenten lager?

**Comment by Lillebo** [comment]
Hei 🙂

I første omgang er dette komponent-biblioteket laget for applikasjoner som lages i NAV, og er ikke noen standard som skal gjelde for alle offentlige digitale løsninger (selv om alle står fritt til å bruke biblioteket om de vil).

De aller fleste komponenten er delt i en JS-pakke og en CSS-pakke. F.eks. finner du både [nav-frontend-ekspanderbartpanel](https://github.com/navikt/nav-frontend-moduler/tree/master/packages/node_modules/nav-frontend-ekspanderbartpanel) (som er JS-komponenten) og [nav-frontend-ekspanderbartpanel-style](https://github.com/navikt/nav-frontend-moduler/tree/master/packages/node_modules/nav-frontend-ekspanderbartpanel-style) (som er CSS-stilene for komponenten). Normalt er JS-komponentene avhengig av CSS-stilene, men ikke motsatt. 

Du står dermed fritt i å benytte kun style-pakken, og heller bygge din egen HTML utenom - hvis du ikke ønsker å bruke React eller Javascript overhodet. Hvis du går inn på http://design.nav.no vil du finne eksempler på ren HTML-kode for de fleste komponentene under "Utviklerdokumentasjon", som f.eks. her for Ekspanderbartpanel:

<img width="798" alt="screen shot 2018-07-02 at 15 49 08" src="https://user-images.githubusercontent.com/74510/42167836-848dd3d4-7e0f-11e8-8b19-40731fb00901.png">

**Comment by polterguy** [comment]
Jeg leste om dere på digi.no i dag, og det er ett bra initiativ dere har gjort her synes jeg. Et ganske _"rent"_ UI, som føles _"lett"_ å følge. Jeg ville muligens ha valgt en mer generisk fremgangsmåte da, ved bruk av rene CSS komponenter, med (opsjon) JavaScript addons da, men greit - Da ville dere stått mer fritt til å bytte ut underliggende plattform, både på front end og back end.

Ville dere hatt noe imot at jeg porter dette til rene CSS filer ...?

Jeg ser mesteparten uansett er lisensiert som MIT, så det bør vel neppe være noe problem ...?

PS - design.nav.no laster forøvrig ikke ...

**Comment by polterguy** [comment]
Psst, ser dere bruker PNG'er som ikoner. Er det en spesiell årsak til at dere ikke bruker ikoner som kan enklere resizes, slik som f.eks. SVG ikoner osv ...?

**Comment by eirslett** [comment]
Guiden er også deployet her: https://navikt.github.io/nav-frontend-moduler/

**Comment by polterguy** [comment]
Takk :)
