### ISSUE TITLE
Import av nav-frontend-modal gir lint-feil

### ISSUE THREAD

**Issue by helgefredheim** [navikt/aksel#336]
Vi får lint-feil når vi prøver å importere nav-frontend-modal:

```
  2:19  error  Missing file extension for "nav-frontend-modal"  import/extensions
```

Kan dette skyldes en feil i modulen? Den ligger som en avhengighet under dependencies i package.json.

**Comment by Lillebo** [comment]
Lurer på om denne ble fikset av #341. Får du oppdatert og testet?

**Comment by Lillebo** [comment]
Lukker pga. inaktivitet.
