### ISSUE TITLE
Fjerne background-color fra selectContainer

### ISSUE THREAD

**Issue by winsvold** [navikt/aksel#366]
Trengs backgroundcolor her?

Med (hvite hjørner):
![image](https://user-images.githubusercontent.com/29202094/43837739-be707512-9b19-11e8-8531-21f04e104a70.png)

Uten:
![image](https://user-images.githubusercontent.com/29202094/43837755-c9ab8156-9b19-11e8-8fda-88b95157cc91.png)

https://github.com/navikt/nav-frontend-moduler/blob/0f81229c8ded665c92966c64eba545a4ff78df74/packages/node_modules/nav-frontend-skjema-style/src/select.less#L4

**Comment by Lillebo** [comment]
Hm, ser ikke noe grunn til å ha den nei. Lager du en PR?

**Comment by winsvold** [comment]
Can do!
