### ISSUE TITLE
Ikke sette margin: 0 på typo-klasser

### ISSUE THREAD

**Issue by helgefredheim** [navikt/aksel#375]
Det er uheldig at typo-klasser setter margin: 0, da de med dette overstyrer andre klassers avstander.

**Comment by nutgaard** [comment]
Har vært borti problemstillingen selv, f.eks ved `<span class="typo-normal blokk-m" />` så nullstilte typo-klassen marginen. Men dette skal være løst i nyeste versjon av frontendbiblioteket? Har du andre tilfeller hvor dette er problematisk? 

Problemet med å ikke sette `margin: 0` er at det bryter med en av hoved-prinsippene i biblioteket om at ingen elementer skal ta mer plass enn nødvendig. Et annet issue med å sette margin er at det ikke finnes en standard for som fungerer for alle, og da havner man fort tilbake i samme problemstilling.

**Comment by Lillebo** [comment]
Lukker pga. inaktivitet.
