### ISSUE TITLE
Ekskpanderbartpanel legger seg over dropdownmeny

### ISSUE THREAD

**Issue by PerOlavM** [navikt/aksel#380]
Ekspanderbartpanel har en z-index på 100. Hvorfor? 
Gjør at de legger seg over hovemenyen på mindre skjermflater.
Eksempler:
https://tjenester.nav.no/veiledearbeidssoker/?sprak=nb
https://tjenester.nav.no/veiviserarbeidsgiver/tilrettelegge/slik-gar-du-fram

**Comment by Lillebo** [comment]
Hm, var ikke klar over det. Virker ganske unødvendig ja.

**Comment by erlendev** [comment]
Dette virker merkelig, og skal trygt kunne fjernes (og hvis ikke er det fordi noen bruker nav-frontend riv ruskende galt).

Koden for dette ser ut til å komme fra en mixin i `nav-frontend-paneler-style`:
https://github.com/navikt/nav-frontend-moduler/blob/master/packages/node_modules/nav-frontend-paneler-style/src/mixins.less
