### ISSUE TITLE
Skrive ut bekreftCheckboksPanel fra inputPanel.less

### ISSUE THREAD

**Issue by erlendev** [navikt/aksel#384]
`inputPanel.less` prøver idag å dekke generell styling for litt mange ting på en gang:

- RadioPanel
- CheckboksPanel
- BekreftCheckboksPanel

Fordi det resulterer i selektorer som f.eks. dette:
```
.radioPanel {
  &.inputPanel {
    &--checked {
      cursor: default;

      /**
       * Den siste :not-selectoren her er egentlig unødvendig, men må være med for å oppnå samme
       * spesifisitet som stilene de overrider i 'input-panel.less' (slik at vi unngår !important)
       */
      &:hover:not(.inputPanel--disabled):not(.bekreftCheckboksPanel) {
        background-color: rgba(0, 103, 197, 0.2);
        border: 1px solid transparent;
        box-shadow: none;

        .inputPanel__field + .inputPanel__label:before {
          background-color: @navBla;
          // todo: remove after rewrite of inputPanel styling
          background-image: @checkWhite;
        }
      }
    }
```

Koden blir med dette ekstremt vanskelig å lese / debugge, og fører også til feil (senest #383). Mulig løsning her er å skrive ut BekreftCheckboksPanel helt fra inputPanel.less. Kanskje også å skrive vekk inputPanel.less fullstendig til fordel for å style `RadioPanel`, `CheckboksPanel` og `BekreftCheckboksPanel` hver for seg.

**Comment by Lillebo** [comment]
Enig 👍
