### ISSUE TITLE
Forbedringsmuligheter på Bekreftcheckbokspanel

### ISSUE THREAD

**Issue by solhell** [navikt/aksel#395]
Jeg ser noen forbedringsmuligheter på markeringer på Bekreftcheckbokspanel (http://design.nav.no/#/components/bekreftcheckbokspanel):

1. Det mangler egendefinert fokusmarkering på lenken
2. Fokusmarkering på hele området når fokus er på avkrysningsboksen er ikke helt heldig - det bør være 1:1-forhold mellom markering og antall aktive objekter, og her blir det en lenke inne i det markerte området i tillegg til avkrysningsboksen. Legg heller fokusmarkering rundt helheten av `<input>` og `<label>`
3. Kontrasten på fokusmarkeringer bør generelt forholde seg til WCAG 1.4.11 Non text contrast, altså 3.0:1. Gulfargen her er ganske langt unna allerede mot hvit, og her er det bakgrunnsfarge både bak og i boksen = kontrast på ca 1.6:1.

**Comment by Lillebo** [comment]
Takk for veldig gode innspill 👍

**Comment by StaleKjone** [comment]
Feilmeldingene har trolig også et forbedringspotensial. Rød skrift på rød/rosa bakgrunn uten markering rundt av noe slag. Kanskje gjenbruke det som er laget for Alertstripe?

Ønsker helst at feilmeldinger generelt sett vurderes forbedret dersom det lar seg gjøre.

**Comment by Lillebo** [comment]
Enig. Vi har fått flere innspill på forbedringsmuligheter for feilmeldinger. Vi kommer nok til å ta en runde på disse om ikke så lenge.
