### ISSUE TITLE
Kontrast på ikke-tekstlig innhold

### ISSUE THREAD

**Issue by solhell** [navikt/aksel#396]
Ser at det gjennomgående bør gjøre en jobb på kontrast på ikke-tekstlig innhold, i henhold til WCAG 1.4.11 Non text contrast. Noen eksempler:

- Kantlinje på tekstfelt mot enten innvendig farge eller bakgrunnsfarge
- Fokusmarkering mot bakgrunn
- Kontrast mellom fokusmarkering og tekst, for eksempel på lenke i tekst - her er den nede på 3.6:1 
![image](https://user-images.githubusercontent.com/20128085/47560004-50ed3c00-d917-11e8-9380-df4c90083d6b.png)

**Comment by Lillebo** [comment]
Takk 🙂 Vi skal ta en gjennomgang av dette 👍
