### ISSUE TITLE
NavFrontendSpinner kaster en warning

### ISSUE THREAD

**Issue by vegarsti** [navikt/aksel#40]
´NavFrontEndSpinner´ gir følgende warning i bruk:

```
Accessing PropTypes via the main React package is deprecated ...
```

For å reprodusere, bare render en komponent av denne typen.

Finnes det en fiks for dette?

**Comment by nutgaard** [comment]
Hei, 
Denne typen warnings kom med den nye versjonen av react (15.5.0?), men skal være fikset i hele nav-frontend. Så dobbeltsjekke at du bruker siste versjon av avhengigheten 0.1.3 

Om det fortsatt dukker opp kan jeg ta en nærmere titt i morgen.

**Comment by vegarsti** [comment]
Takk! Det kan godt hende det er det, skal ta en titt i morgen!

tor. 20. jul. 2017 kl. 16.25 skrev Nicklas Utgaard <notifications@github.com

**Comment by vegarsti** [comment]
Hm! Vi har 0.1.3 på nav-frontend-spinner, det var det du mente, sant? Har React 15.6.1

**Comment by nutgaard** [comment]
Sjekket litt mer nå, og `nav-frontend-spinner` bruker proptypes riktig. Men den har en transitiv avhengighet til `nav-frontend-ikoner-assets` som blir autogenerert ved hjelp av `react-svg-icon-generator` og her brukes `React.PropTypes` som nå da gir en warning.

De merged inn en PR fra oss der 18. juni, men har ikke publisert pakken enda. 
Laget ett issue til dem https://github.com/blueberryapps/react-svg-icon-generator/issues/21 på dette, så forhåpentligvis kommer det en ny versjon relativt raskt og da kan dette problemet løses.

**Comment by vegarsti** [comment]
Konge! Tusen takk!

fre. 21. jul. 2017 kl. 14.50 skrev Nicklas Utgaard <notifications@github.com

**Comment by nutgaard** [comment]
Løst av #81 merged inn i #84
