### ISSUE TITLE
CSS i validering av skjema er kontekst-basert

### ISSUE THREAD

**Issue by helgefredheim** [navikt/aksel#42]
Det ser ut som en del styling av validering av skjemaelementer, herunder visning av feilmeldinger og feilområder er kontekst-basert. Kan vi endre dette? 

F.eks:

`.skjema--harFeil .skjema__feilomrade { background-color: pink; }`

kan endres til

`.skjema__feilomrade--harFeil { background-color: pink; }`

og: 

`.skjemaelement--harFeil .skjemaelement__input { border-color: red; }`

kan endres til: 

`.skjemaelement__input--harFeil { border-color: red }`

Dette vil gjøre selektorene mindre koblet til DOM-struktur.

**Comment by nutgaard** [comment]
Jeg ser ingen problemer med det. 👍 Men kan være at andre har andre meninger.

**Comment by nutgaard** [comment]
Løst av #43
