### ISSUE TITLE
Bug: AlertStripe ver. 1.0.30 crasher React, finner ikke moduler.

### ISSUE THREAD

**Issue by PeterRydberg** [navikt/aksel#435]
Den nyeste oppdateringen av nav-frontend-alertstriper gjør at React ikke finner moduler, enten det står at den ikke finner 'react' eller 'prop-types'.

`JSX element class does not support attributes because it does not have a 'props' property.`

Reproduseres ved å installere nyeste versjon av nav-frontend-alertstriper, dvs. 1.0.30. I dokumentasjonen står det fremdeles at nyeste versjon skal være 1.0.29. Har en oppdatering endret på noe her?

**Comment by Lillebo** [comment]
Hm, klarer ikke reprodusere den feilmeldingen - kan du forklare litt mer rundt oppsett og hva du gjør?

Men det stemmer at det er en bug på nye nettsiden som viser siste versjon av pakkene som en patch eldre enn det som egentlig gjelder (jobber med saken). [Siste versjon som står på npmjs.com](https://www.npmjs.com/package/nav-frontend-alertstriper?activeTab=versions) er uansett riktig her.

**Comment by NunoCardoso** [comment]
I upgraded today, and it works. Did you ran 'npm install'?

**Comment by PeterRydberg** [comment]
I've removed package-lock and wiped node_modules, still the problem persists. I even deleted the repository and reinstalled, and the project still won't compile. It seems to occasionally work when manually changing package.json and reinstalling, but other times it does not. It might be a problem on my part (we're using a less to css compiler), but I am unsure what the problem might be. Previously all the components worked fine. My current compilation error is this:

> Error: ENOENT: no such file or directory, stat 'C:\Users\peter\Webutvikling\generiskurl\frontend\src\~nav-frontend-typografi-style'
>     at Object.statSync (fs.js:815:3)
>     at Object.findLessImportsInFile (C:\Users\peter\Webutvikling\generiskurl\frontend\node_modules\less-watch-compiler\dist\lib\filesearch.js:13:20)
>     at Object.fileWatcher (C:\Users\peter\Webutvikling\generiskurl\frontend\node_modules\less-watch-compiler\dist\lib\lessWatchCompilerUtils.js:225:38)
>     at C:\Users\peter\Webutvikling\generiskurl\frontend\node_modules\less-watch-compiler\dist\lib\lessWatchCompilerUtils.js:86:40
>     at C:\Users\peter\Webutvikling\generiskurl\frontend\node_modules\less-watch-compiler\dist\lib\lessWatchCompilerUtils.js:63:75
>     at FSReqWrap.oncomplete (fs.js:153:5)

I am using Windows and our project is made with 'react-create-app' and TypeScript. We import our component styles using '[at]import "~nav-frontend-typografi-style";'

Our package.json looks like this:

> {
>   "name": "generiskurl",
>   "version": "0.1.0",
>   "private": true,
>   "dependencies": {
>     "@types/react-redux": "^7.0.0",
>     "@types/react-router-dom": "^4.3.1",
>     "babel-polyfill": "^6.26.0",
>     "babel-runtime": "^6.26.0",
>     "classnames": "^2.2.6",
>     "nav-frontend-alertstriper": "^1.0.29",
>     "nav-frontend-alertstriper-style": "^0.2.50",
>     "nav-frontend-core": "^4.0.6",
>     "nav-frontend-etiketter": "^1.0.17",
>     "nav-frontend-etiketter-style": "^0.3.15",
>     "nav-frontend-ikoner-assets": "^0.2.31",
>     "nav-frontend-js-utils": "^1.0.6",
>     "nav-frontend-knapper": "^1.0.15",
>     "nav-frontend-knapper-style": "^0.3.14",
>     "nav-frontend-lukknapp": "^1.0.18",
>     "nav-frontend-lukknapp-style": "^0.2.17",
>     "nav-frontend-modal": "^1.0.25",
>     "nav-frontend-modal-style": "^0.3.27",
>     "nav-frontend-paneler-style": "^0.3.13",
>     "nav-frontend-skjema": "^1.0.25",
>     "nav-frontend-skjema-style": "^1.0.10",
>     "nav-frontend-typografi": "^2.0.7",
>     "nav-frontend-typografi-style": "^1.0.10",
>     "prop-types": "^15.7.1",
>     "react": "^16.8.1",
>     "react-dom": "^16.7.0",
>     "react-modal": "^3.8.1",
>     "react-redux": "^6.0.0",
>     "react-router-dom": "^4.3.1",
>     "react-scripts": "^2.1.3",
>     "redux": "^4.0.1",
>     "redux-thunk": "^2.3.0",
>     "tslint": "^5.12.1",
>     "tslint-config-airbnb": "^5.11.1",
>     "tslint-react": "^3.6.0"
>   },
>   "scripts": {
>     "start:js": "react-scripts start",
>     "build:js": "react-scripts build",
>     "start:css": "less-watch-compiler --config less.json",
>     "build:css": "less-watch-compiler --run-once --config less.json",
>     "start": "npm-run-all -p start:*",
>     "build": "npm run build:css && npm run build:js",
>     "test": "react-scripts test",
>     "test:u": "react-scripts test -u",
>     "lint": "tslint --project .",
>     "lint:fix": "tslint --project . --fix",
>     "eject": "react-scripts eject",
>     "e2e": "cypress run",
>     "e2e:verify": "cypress verify",
>     "cypress:open": "cypress open"
>   },
>   "devDependencies": {
>     "@types/enzyme": "^3.1.17",
>     "@types/enzyme-adapter-react-16": "^1.0.3",
>     "@types/jest": "^23.3.14",
>     "@types/node": "^10.12.18",
>     "@types/react": "^16.7.20",
>     "@types/react-dom": "^16.0.11",
>     "cypress": "^3.1.5",
>     "enzyme": "^3.8.0",
>     "enzyme-adapter-react-16": "^1.9.1",
>     "enzyme-to-json": "^3.3.5",
>     "less": "^3.9.0",
>     "less-plugin-npm-import": "^2.1.0",
>     "less-watch-compiler": "^1.13.0",
>     "lodash.throttle": "^4.1.1",
>     "npm-run-all": "^4.1.5",
>     "redux-mock-store": "^1.5.3",
>     "ts-jest": "^23.10.5",
>     "typescript": "^3.2.4",
>     "webpack-dev-server": "^3.1.11"
>   },
>   "browserslist": [
>     ">0.2%",
>     "not dead",
>     "not ie <= 11",
>     "not op_mini all"
>   ]
> }

**Comment by Lillebo** [comment]
Denne linjen gir et hint om at det er noe krøll med hvordan dere har satt opp `less-plugin-npm-import`:
```
Error: ENOENT: no such file or directory, stat 'C:\Users\peter\Webutvikling\generiskurl\frontend\src~nav-frontend-typografi-style'
```
Ettersom kompilatoren forsøker å gjøre oppslag på path `src~nav-frontend-typografi-style` - som jo blir feil. Hvordan er det dere angir npm-prefix til `less-plugin-npm-import`? Har dere en `less.json`-fil på rot i prosjektet? Hvordan ser den ut? Den pluginen opererer med `npm://` som default npm-prefix - som da må byttes til `~` hvis dere ønsker å bruke det.

Se gjerne på eksempel-oppsett for Create React App som vi har satt opp her (se f.eks. `less.json` fila på rot der): https://github.com/navikt/nav-frontend-moduler/tree/master/examples/cra

**Comment by PeterRydberg** [comment]
Beklager sent svar, laptopen har tatt kvelden permanent så det er lite jeg får testet personlig ila helgen (skriver via mobil).

Jeg glemte å nevne at vårt prosjekt baserer seg på det du lenket til, så less.json er her identisk. Komponentene har jo tross alt fungert fint før, så prefix burde fungere fint. Jeg mistenker at dette faktisk er et npm-relatert problem, så jeg får teste videre når jeg får tilgang til en PC igjen. Takk for hjelp!

**Comment by PeterRydberg** [comment]
Da har jeg endelig fått satt opp Linux på en (lite ideell) låne-PC, og jeg kan se at problemene oppstår ved bruk av en egen package (redux-oidc) eller dens dependencies. Det betyr med andre ord at NAV-komponentene ikke har skyld i feilen, men det finnes et annet problem som jeg må rette opp i. Derfor er det bare å lukke issuet om dere ikke har andre kommentarer, så tusen takk for hjelpen :)

**Comment by Lillebo** [comment]
Så bra at du fant ut av det 🙂Bare si ifra hvis det skulle være noe annet.
