### ISSUE TITLE
Støtte for SASS

### ISSUE THREAD

**Issue by dervism** [navikt/aksel#441]
I NAV utvikler vi mange applikasjoner som er basert på Create React App (CRA). Out-of-the-box har CRA kun støtte for SASS og ikke LESS, og det ser heller ikke ut som dette vil komme med det første.

En løsning som har funket i første omgang - har vært å legge inn en lessc også endre byggeprosessen slik at lessc først kompilerer til CSS før resten av applikasjonen bygges med CRA.

#4 ble lukket i 2017 uten at det da var støtte for laste ned avhengighetene til SASS (slik jeg forstod issuen). Er det mulig å gjøre noe med dette nå?

**Comment by Lillebo** [comment]
Jeg har ikke brukt det selv, men @nutgaard har visst god erfaring med [Craco](https://www.npmjs.com/package/@craco/craco), som visstnok lar deg legge til støtte for LESS i Create React App uten å måtte ejecte (se [denne Slack-tråden](https://nav-it.slack.com/archives/C6HJFRRMY/p1565950570013000)). Antar at dette fortsatt fordrer at utvikleren skriver LESS hvis hen ønsker å importere variabler, mixins osv. fra `nav-frontend`-pakker i egne stilark, ettersom imports på tvers av disse formatene [virker å være umulig](https://stackoverflow.com/questions/25221635/can-i-import-a-less-file-into-sass/25222581).

Blir forøvrig gjerne med på en diskusjon om vi skal vurdere å skrive om fra LESS til SASS i pakkene våre.
