### ISSUE TITLE
Feilmelding til radio-komponent

### ISSUE THREAD

**Issue by nutgaard** [navikt/aksel#45]
Checkboks støtter per i dag feilmeldinger, er dette noe også bør legges til for radio-knapper? 

Er det behov? Eller løses dette stortsett ved hjelp av `SkjemaGruppe`?

**Comment by erlendev** [comment]
Mulig @sergiohaisch har noen tanker om dette? Er det tilfeller der man ønsker å highlighte feil for kun en radioknapp, istedetfor eller i tillegg til å vise feilmelding på det overordna skjemaelementet? Hvis ikke foreslår jeg at vi lukker og gjenåpner dersom behovet skulle oppstå.

**Comment by erlendev** [comment]
Har avklart med @sergiohaisch. Det gir egentlig ikke mening å ha support for feil hverken på individuelle checkbox- eller radio-elementer i og med at de aldri står alene. Feilene skal være knyttet til antallet du har huket av på, f.eks. "maks to valg" for en gruppe checkbokser og "gjør et valg" for en gruppe radioknapper, ikke til true/false verdien av en radio/checkbox. 

Egentlig bør vi jo fjerne support for feilmelding på individuell checkbox, vet du om det blir brukt noe sted @nutgaard? Lukker denne og oppretter ny issue #47
