### ISSUE TITLE
Soruce Sans Pro font-face ser ikke bra ut i Chrome

### ISSUE THREAD

**Issue by otenav** [navikt/aksel#46]
Font-face src for Source Sans Pro inneholder en base64 encoded woff. Denne fonten ser ikke bra ut i min browser (Chrome59 + Windows10). 

Jeg overstyrte denne fonten, og brukte i stedet en base64 encoded versjon av https://fonts.google.com/specimen/Source+Sans+Pro, og dette ga en mye bedre font.

Er det noe galt med woff fonten, eventluelt hvordan denne encodes til base64?

**Comment by nutgaard** [comment]
Vi har sett noen problemer med den fonten på firefox tidligere, men ikke i chrome. Er dette på en vanlig laptop, eller er det gjennom en VM eller tilsvarende?

Kan du forklare hvordan du overstyrte fonten, lenke til din base64-encodede versjon etc?
Vi har som sagt ikke sett noen problemer her tidligere, så greit med litt mer info. :)



### Hvordan fontene blir laget i dag.
Font-filene vi bruker er også hentet fra fonts.google.com, og ligger [her](https://github.com/navikt/nav-frontend-moduler/tree/master/packages/node_modules/nav-frontend-typografi-style/assets). 

Woff-filene blir encoded og embedded via ett gulp-script ([gulpfile](https://github.com/navikt/nav-frontend-moduler/blob/master/gulpfile.js#L96), [gulpfile](https://github.com/navikt/nav-frontend-moduler/blob/master/gulpfile.js#L72)) som lager less-filene [her](https://github.com/navikt/nav-frontend-moduler/tree/master/packages/node_modules/nav-frontend-typografi-style/src).

**Comment by otenav** [comment]
Dette skjer ikke på laptop, men på VM, andre fonter ser ikke helt optimale ut de heller, men det er betydelig værre for Source Sans Pro.

Jeg brukte fontene fra https://fonts.google.com/specimen/Source+Sans+Pro og brukte encoder https://www.giftofspeed.com/base64-encoder/. Deretter laget jeg en egen css hvor jeg hadde:
`@font-face {
    font-family: 'Source Sans Pro';
    font-weight: 400;
    font-style: normal;
    src: url(data:application/font-woff;base64,MIN_EGEN_BASE64_KODE
}`

Dette ga en betydelig forbedring og jeg vil si at de fikk tilsvarende kvalitet som de andre fontene på min maskin.

(Filene jeg lastet ned fra fonts.google.com var ttf, ikke woff.)

**Comment by nutgaard** [comment]
Spørs om det ikke er forskjellen på ttf og woff som er årsaken da. 
Men dobbeltsjekk gjerne at riktig font ble brukt hos deg (computed-fanen i chrome devtools), ser at du har `font-weight: 800` og `font-woff`. Og om jeg ikke husker helt feil så er chrome nokså kresen på når den bruker eksterne fonter. Så vil bare være sikker.

Ved problemer med firefox + VM tror jeg vi konkluderte med at det var pga manglende hardware acceleration på VMen. Men om vi begynner å se dette i chrome også, så må vi kanskje ta en runde på om vi skal gjøre noen endringer på font-oppsettet.

**Comment by otenav** [comment]
Nå har jeg testest både SourceSansPro-Regular.ttf fra google og Source-Sans-Pro-regular.woff fra nav-frontend-typografi-styles. Jeg brukte samme base64 converter. Font-weight er 400. Jeg ser at ttf rendrer fint, mens woff ikke gjør det. 

Jeg sjekket også at det er riktig font som lastes og brukes i computed-fanen i devtools.

**Comment by nutgaard** [comment]
Jeg er tilbake på jobb i morgen, så kan ta en titt på dette da. Kan hende dette er samme problem som vi har sett i firefox tidligere. Men om det også er et problem på chrome/IE så må vi ta en runde for å finne en fiks på dette. 

Jeg kan teste om dette er et problem på win10 + chrome - VM, men tror VMen er årsaken her. :/

**Comment by erlendev** [comment]
Lukkes da det ser ut til å gjelde alle fonter (også vanlig Arial) og er et VM-spesifikt problem.

**Comment by otenav** [comment]
@nutgaard @erlendev, Jeg har testet dette på en maskin som ikke kjører VM. Testet det på Windows 7 med Chrome Versjon 60.0.3112.113 (Offisiell delversjon) (64-bit).

Jeg får akkuratt samme problemer med font på denne maskinen, så jeg mener at dette issue'et bør gjennåpnes.

**Comment by otenav** [comment]
![screen](https://user-images.githubusercontent.com/29566394/30097034-d790b7a6-92db-11e7-9a84-e2f572ef89ff.png)

Legger ved screenshot som viser hvordan fontene ser ut.

**Comment by nutgaard** [comment]
Lukkes da saken har vært stale i lengre tid, og "kan ikke fikses" - Frode
