### ISSUE TITLE
nav-frontend-ekspanderbartpanel (versjon 1.0.25) feiler på universell utforming Axe-verktøyet

### ISSUE THREAD

**Issue by jcpgithub** [navikt/aksel#462]
`nav-frontend-ekspanderbartpanel` feiler på universell utforming (versjon 1.0.25) 
Bruk UU-verktøyet Axe chrome-plugin.

Klager på at attributt verdien til  `aria-control` er ugyldig når `nav-frontend-ekspanderbartpanel` er kollapset.

![Screenshot 2019-04-23 at 12 35 12](https://user-images.githubusercontent.com/462431/56575295-aacc7700-65c5-11e9-9e2c-9cb5ebde27bf.png)
![Screenshot 2019-04-23 at 12 36 45](https://user-images.githubusercontent.com/462431/56575306-aef89480-65c5-11e9-8e07-cad267e5b835.png)

**Comment by Lillebo** [comment]
Takk 🙂 Dette kommer nok av at panelet [bruker `UnmountClosed`-versjonen av `react-collapse` som default](https://github.com/navikt/nav-frontend-moduler/blob/master/packages/node_modules/nav-frontend-ekspanderbartpanel/src/ekspanderbartpanel-base-pure.tsx#L77) - hvor det kollapsbare innholdet blir fjernet fra DOM når det skjules. Det er mulig å overstyre ved å sette `<Ekspanderbartpanel renderContentWhenClosed={true} />`, men vi bør fikse slik at `aria-controls` hensyntar dette.

**Comment by jcpgithub** [comment]
Takk, da bruker jeg renderContentWhenClosed
`{
      ...{
             renderContentWhenClosed: true
         }
}`
