### ISSUE TITLE
NPM-pakkene inkluderer DocInfo for komponentene og blir unødvendig tunge

### ISSUE THREAD

**Issue by Lillebo** [navikt/aksel#466]

**Comment by KenAJoh** [comment]
Foreslått fungerende løsning per nå: 
- Skrive om gulpfile til å ha to outputs av moduler: `/lib` og `/docs`. Docs vil da inneholde versjonen med docinfo generert og blir ikke lastet opp til npm
- Skrive om `components.js` under guideline-app til å ta i bruk modulene under `/docs` istedenfor `/lib`

Problemer med denne løsningen er at fks `tsc -w -d src/bekreft-checkboks-panel.tsx --jsx react --outDir lib --lib DOM,ES2015,ES2016,ES2017` vil oppdatere modulen for development appen, men ikke guideline-app noe som betyr utvikler må kjøre `gulp build` for hver endring.

**Comment by KenAJoh** [comment]
Løsningen var ikke like enkelt som antatt, da require.context i data/components/components.js ikke ikke laster inn alle pakkene hvis "main" ikke er satt til "/doc" istedenfor "/lib" når de hentes. Eventuell løsning på dette må undersøkes først
