### ISSUE TITLE
Fjerne support for feilmelding på individuell Checkbox

### ISSUE THREAD

**Issue by erlendev** [navikt/aksel#47]
En checkbox står aldri alene, og feil tilknyttet checkbox skal knyttes opp imot antallet checkbox'er som er huket av, ikke opp imot true/false verdien av en bestemt checkbox.

Blir dette brukt noe sted idag?

Relatert til #45

**Comment by nutgaard** [comment]
I løsningen mininnboks brukes en enkeltstående checkboks til å markere om vilkår er lest. Dette er dog på utsiden, men det finnes kanskje tilsvarende tilfeller av dette på nye internløsninger også.


![image](https://user-images.githubusercontent.com/1413417/29072838-b57ee3a2-7c49-11e7-89ff-15b920012b48.png)

**Comment by erlendev** [comment]
Lukkes etter diskusjon på frontend forum
