### ISSUE TITLE
TextArea mulighet å oppgi når tellerTekst skal vises

### ISSUE THREAD

**Issue by alexander-svendsen** [navikt/aksel#478]
Hei, 
Vi har et ønske å kunne sende inn et parameter til TextArea componentenen når tellerteksten skal vises.

Type hvis det er mindre enn 50 tegn igjen, vis teller teksten.

Per i dag så må vi hacke dette inn ved å selv endre tellerTeksten sendt inn

**Comment by Lillebo** [comment]
Hm, kan dere fortelle litt rundt bakgrunnen for dette? Er det et rent design-ønske? 

I utgangspunktet litt skeptisk til å skjule denne tegn-begrensningen frem til begrensningen nærmer seg. Brukeren vil jo da begynne å skrive uten å bli informert om at det gjelder en tegn-begrensning før etter at de har skrevet endel - hvor de kanskje vil bli nødt til å omformulere alt det de har skrevet så langt for å få plass til resten de ønsker å få med.

Samtidig er jeg litt fan av hvordan Twitter har løst dette. Kanskje vi kan prøve å få til noe lignende?

![May-03-2019 09-29-35](https://user-images.githubusercontent.com/74510/57124453-30021980-6d86-11e9-8387-41a9fd30c22f.gif)

**Comment by alexander-svendsen** [comment]
Det er et rent design ønske.
I løsningen jeg jobber i nå så har vi en tekst boks som maks skal inneholde 500 tegn, men vi ønsker først å vise telleren når brukeren har 50 tegn igjen. 
Vi har prøvd å gjøre brukeren obs på at dette ikke skal inneholde en lang tekst ved å gjøre tekst boksen relativt liten, så brukeren vil naturlig tro at det skal skrives lite. Hvis vi viser brukeren teksten: "Du har 500 tegn igjen", så tror jeg brukeren tro han burde skrive mye mer enn de 2 settningene vi forventer kommer inn. 

En annen ting jeg har tenkt på er at vi har flere steder ingen begrensninger på antall tegn, men i TextArea komponentet må man oppgi maxlenght og vil få opp teller-teksten. Så i disse tilfellene så har vi hacket oss rundt problemet, ved å oppgi en tom teller tekst og har en vilt stor maxLength.
Hvis vi kunne oppgi når vi ønsker å vise teller teksten så hadde det løst litt enklere denne problematikken.

**Comment by Lillebo** [comment]
Hm, skjønner. Tror nok dessverre vi blir nødt til å vise tegn-begrensningen på en eller annen måte sålenge den gjelder. Men skjønner at det er uheldig å gi brukeren inntrykk av at de MÅ fylle boksen med tusenvis av tegn også. Mistenker den Twitter-versjonen kan fikse noe av det. Vi slipper i alle fall teksten "Du har X tegn igjen" - hvor det spesifikke antall tegn forblir noe vagt inntil limiten nærmer seg.

Uansett enig i at tegn-begrensning bør være valgfritt. Var ikke klar over at komponenten alltid krevde et maks antall tegn. Det skal vi i alle fall kunne fikse relativt kjapt.

**Comment by alexander-svendsen** [comment]
Defaulten på maxlegnth er 2000, Så det vil alltid bli vist en tegn-begrensning hvis ikke annet er oppgitt

**Comment by Lillebo** [comment]
Jau, ser det. Tenker den burde kunne være `undefined`.

**Comment by alexander-svendsen** [comment]
Jeg pusher problemstillingen videre til designerne våre. Så tar de en prat internt og med Sergio. Er dumt å ha et avik her med hvordan teams gjør det.

Tenker jeg aventer med å fjerne tekst telleren i koden vår ellers til de har bestemt seg hvordan det skal gjøres :)
