### ISSUE TITLE
Mulig å legge til tekst foran hjelpetekst-komponenten

### ISSUE THREAD

**Issue by jcpgithub** [navikt/aksel#479]
Mulig å legge til "tekst" foran hjelpeikonet. F.eks slik ?
![image](https://user-images.githubusercontent.com/462431/57074372-ed880080-6ce3-11e9-8bd7-eda7c74cfbe5.png)

https://github.com/navikt/nav-frontend-moduler/tree/master/packages/node_modules/nav-frontend-hjelpetekst

**Comment by KenAJoh** [comment]
Videre diskusjon her: navikt/Designsystemet/issues/136
