### ISSUE TITLE
Problem med fokus, tastaturnavigasjon og ekspanderende paneler

### ISSUE THREAD

**Issue by otenav** [navikt/aksel#48]
- Jeg har to ekspanderende panel, det første innholder en knapp. 
- Jeg bruker tastaturet og navigerer rundt på siden
- Jeg tab'er meg frem til det første ekspandererende panelet og trykker enter for å åpne dette. Inne i panelet er det en knapp. 
- Jeg finner ut at dette var feil panel, og trykker på enter for å lukke panelet igjen. Jeg trykker deretter tab og enter for å åpne det neste panelet. Og her går det feil: I stedet for å sette fokus på neste panel, så har knappen inne i det første panelet fått fokus. Og siden jeg trykket enter, i tro om at dette ville åpne det andre panelet, har dette medført at jeg istedet klikket på knappen.

Dette oppstår bare om man er rask med tastaturnavigasjonen, og om man ikke legger merke til hvor fokus markøren egentlig er. Selv om det ekspandernede panelet ser ut som helt lukket, ser det ut til at transition effekten ikke er fullført, og at det er en liten tidsluke hvor man kan sette fokus til elementer inne i et tilsynelatende lukket panel.

I mitt tilfelle åpner bare knappen en popup og det skjer ikke stort annet en det. Men om knappen for eksemplevis er en slettknapp, kan det jo oppstå uønskede saker på grunn av dette.

**Comment by nutgaard** [comment]
Fint at du rapporterter, stemmer nok det du sier. Innholded innenfor en react-collapse blir værende frem til animasjonen anses som helt ferdig, og siden animasjonen er fysikkbasert så kan det se ut som den er ferdig før den faktisk er det.

Tar gjerne imot forslag til hvordan dette kan løses, enten her eller som PRs.

**Comment by nutgaard** [comment]
@otenav Hva tenker du om å stoppe tabs når lukke-animasjonen fortsatt pågår? E.g så lenge animasjonen ikke har stoppet så kaller vi bare `preventDefault` om vi ser ett keyEvent som tilsvarer tab.

**Comment by nutgaard** [comment]
En annen løsning er å få panelet til å eksponere litt state (via context kanskje?), slik at knappene evt. kan disables hvis lukke-animasjonen er aktiv.

**Comment by otenav** [comment]
Ang. det å stoppe tab når lukke-animasjonen pågår: Vil effektivt hindre bruker å tab'e seg til en skjult knapp. Men vil nok samtidig oppleves som at browseren ikke responderer for de som bare lukker tab'en og navigerer seg videre.

Ved å la panelet disable alle sine children under animasjon, vil man også unngå problemet. Utfordringen her disabled css styling aktiveres og at det kanskje ikke er øsnket sånn rent visuelt.

**Comment by otenav** [comment]
Jeg har også vurdert andre måter:

- Fjerne children fra panelet før lukke animasjonen starter. Dette vil hindre problemet, men kan være en utfordring visuelt, siden panelet tømmes og deretter lukkes.
- Ha en annen animasjonstype som avsluttes raskere, slik at tidsrommet hvor man potensielt kan klikke en usynlig knapp minimerers. Dette vil ikke løse problemet, gjøre det litt mindre sannsynlig at det skjer,
