### ISSUE TITLE
Border på ekspanderbartpanel forsvinner

### ISSUE THREAD

**Issue by yrjanaff** [navikt/aksel#486]
Under testing av en ny applikasjon fant vi en feil i ekspanderbart panel hvor borderen forsvinner ved zoom. Dette ser ut til å kun gjelde for Chrome. Testa i Firefox også, men fikk ikke samme resultat.

Vedlagt skjermdump er tatt ved 80% zoom. Hvilken del av borderen som forsvinner er ikke konsistent.
<img width="586" alt="Screenshot 2019-05-07 at 07 24 16" src="https://user-images.githubusercontent.com/6328554/57292124-4deeb780-70c1-11e9-9332-86ea3c2a46c0.png">

**Comment by Lillebo** [comment]
Hm, tror ikke dette kan anses som en bug med våre komponenter. Dette er nok helt og holdent avhengig av hvordan Chrome rendrer `1px` tykke borders når man zoomer utover. Prøv å zoom ut på denne Github-siden f.eks. (som inneholder mange slike tynne borders) - så ser du raskt at dette også gjelder her.

Det er ingen spesielle tilgjengelighetskrav som omhandler det å kunne _forminske_ nettsidene våre. Ettersom dette ikke virker å være noe problem for brukere som _forstørrer_, så tror jeg vi trygt kan ignorere dette.
