### ISSUE TITLE
jsnext:main-property i package.json-filer utdatert?

### ISSUE THREAD

**Issue by erlendev** [navikt/aksel#49]
Jeg har sjekket litt rundt, og det kan virke som at dette `jsnext:main`-attributtet i package.json-filene på enkeltmoduler i nav-frontend er utdatert og kan erstattes med property-navnet `module`. 

Se bl.a. på diskusjonen her:
https://github.com/webpack/webpack/issues/1979

Litt usikker på hvorfor vi har dette feltet i utgangspunktet og om det er prosjekter som bruker nav-frontend som er avhengig av at vi fortsetter å ha det der, men muligens er det relatert til bruk av redux-form? Ser ut til at også de nå har lagt inn feltet `module`, men har beholdt den gamle `jsnext:main`, antagelig for at ikke noe skal krasje i eksisterende apps.

Se deres nåværende package.json her:
https://github.com/erikras/redux-form/blob/master/package.json

Rollup ser også ut til å ha lagt inn støtte for `module`, som visstnok var de som først introduserte feltet:
https://github.com/rollup/rollup-plugin-node-resolve
https://github.com/rollup/rollup/wiki/pkg.module (les: _Note: Tools such as rollup-plugin-node-resolve and Webpack 2 treat jsnext:main and module interchangeably. They're the same thing, except that module is more likely to become standardised._)

Er det noe vi kan erstatte med `module`, eller bør vi sette begge for å være på den sikre siden?

**Comment by nutgaard** [comment]
Jeg stemmer for å bare bytte til `module`. De som måtte være avhengig av den gamle får heller bumpe webpack versjonen sin.

**Comment by erlendev** [comment]
Fikses av #50
