### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by jksolbakken** [navikt/aksel#499]
I readme til `nav-frontend-skjema` står det at man skal installere `lodash.throttle`. Hva er det som benytter den? Finner ingen spor av bruk. Mulig relatert til #493 ?

**Comment by sasoria** [comment]
Når jeg kjører `npm install` i `/examples/cra` får jeg  denne feilmeldingen:
```
npm ERR! peer dep missing: lodash.throttle@^4.1.1, required by nav-frontend-js-utils@1.0.7
```
Så det er mulig at det er der den brukes, altså i `nav-frontend-js-utils`. Se for eksempel `/nav-frontend-js-utils/src/eventThrottler.tsx`:
```
import * as _throttle from 'lodash.throttle';
...
```
https://github.com/navikt/nav-frontend-moduler/blob/master/packages/node_modules/nav-frontend-js-utils/src/eventThrottler.tsx
