### ISSUE TITLE
Forbedre tekst under Input -> dato

### ISSUE THREAD

**Issue by Lillebo** [navikt/aksel#506]
Vanskelig å forstå hva som menes med denne teksten:
>Det må legges til formatering som gjør at brukere på mobil får opp native-datovelger når denne er nyttig å bruke. Unntak da dette ikke er nyttig er når man skal oppgi fødselsdato og liknende der man ikke har nytte av å se kalenderen.

https://design.nav.no/components/input#dato

**Comment by karinaldw** [comment]
Ikke så sikker hvor den kommer i fra, høres ikke ut som meg... 😊 (Men hvem vet). Så at det var litt diskusjon på slack rundt den. Vi må kanskje se på nettleserstøte av native først?

Fra: Eirik Lillebo <notifications@github.com>
Svar til: navikt/nav-frontend-moduler <reply@reply.github.com>
Dato: tirsdag 2. juli 2019 09:42
Til: navikt/nav-frontend-moduler <nav-frontend-moduler@noreply.github.com>
Kopi: Subscribed <subscribed@noreply.github.com>
Emne: [navikt/nav-frontend-moduler] Forbedre tekst under Input -> dato (#506)


Vanskelig å forstå hva som menes med denne teksten:

Det må legges til formatering som gjør at brukere på mobil får opp native-datovelger når denne er nyttig å bruke. Unntak da dette ikke er nyttig er når man skal oppgi fødselsdato og liknende der man ikke har nytte av å se kalenderen.

https://design.nav.no/components/input#dato<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdesign.nav.no%2Fcomponents%2Finput%23dato&data=02%7C01%7CKarina.Ludwig%40nav.no%7C92f5dd3d2ea84fc1a09808d6fec0dfbb%7C623665341ec3496288699b5535279d0b%7C1%7C0%7C636976501679494341&sdata=KR4LO3LMEDgLc4vlW9eFOJjIc8fpLKRFWx7agMAFjwg%3D&reserved=0>

**Comment by KenAJoh** [comment]
Ser ut som https://design.nav.no/components/input#dato er fjernet.
Henviser til denne diskusjonen om det skulle være nytting navikt/Designsystemet/issues/65
