### ISSUE TITLE
Toggle kodet som input=radio bryter med WCAG

### ISSUE THREAD

**Issue by erlendev** [navikt/aksel#53]
At toggle er kodet som `input=radio` bryter med WCAG, og valgene her bør heller implementeres som vanlige `<button>`s. 

Et bedre navn på denne komponenten er forresten kanskje `Tab` eller `Tabbar`? Toggle kan få det til å høres ut som det er en checkbox e.l.

**Comment by nutgaard** [comment]
Endring av komponentnavn ser jeg på som uproblematisk, men `tab`, `tablist` og `tabpanel` er allerede etablerte betegnelser i WAI-ARIA. Så vi burde se på andre navn tror jeg.

Endring fra `input=radio` til `button` ser jeg ikke helt verdien av. Om det er WCAG 1.3.1 som blir brutt føler jeg den blir mistolket i denne situasjonen. 

Per WCAGs egne sider er test prosedyren for 1.3.1: 
1) Check that the element's semantic meaning is exposed to assistive technology and appropriate for the content of the element.

Elementets semantiske mening er per i dag akkurat likt som en radio-gruppe. Så her ser jeg ingen problemer.

Om det går mer på at "ting skal være kodet slik det ser ut", så er mitt syn er alltid at funksjonell semantikk er viktigere å formidle enn visuell semantikk.

**Comment by erlendev** [comment]
Enig i at visuell semantikk ikke bør spille like stor rolle som det funksjonelle, og jeg tenker nå at vi gir oss selv vel så store problemer med semantikk ved å reimplementere med knapper istedetfor input=radio. En gruppe knapper skal ikke oppføre seg som en radiogruppe, slik som Toggle gjør. UU skulle sjekke ut det litt og holde meg oppdatert på det, så vi tar uansett ikke den omskrivninga nå med en gang.

Men det at det er implementert med `input=radio` har også innvirkning på det funksjonelle ved Toggle. Det gjelder to ting: 

1. Man får ikke tabbet seg gjennom valgene - til det må man bruke piltaster. Om man ser på eksemplet på tilsvarende komponent på [w3.org](https://www.w3.org/WAI/tutorials/menus/styling/#currentnav) (som de har kalt nav), navigerer man med tab og ikke piltaster. Har også sjekket ut tilsvarende funksjonalitet i Twitter Bootstrap, og der gjelder det samme.

2. En annen ting, som jeg er litt usikker på om er ønskelig funksjonalitet, er at aktiv state blir togglet av og på når man navigerer med piltaster. Det er også en konsekvens av at det er implementert som radiogruppe. Om Toggle er tenkt til å skjule/vise innhold i forskjellige tabs er det kanskje mer naturlig at ting aktiveres først ved enter?

Skal se på å lage en PR på de to tingene, men om det blir veldig hacky får vi kanskje se på hva annet enn en radiogruppe som kan egne seg til det her.

**Comment by nutgaard** [comment]
Toggle-komponenten burde ikke brukes for å styre visning av innhold i forskjellige tabs, da er løsningen med `tablist`, `tab` og `tabpanel` å foretrekke (kanskje noe vi burde se på om vi kan løse i nav-frontend?). Sammenligningen med w3's retningslinjer for meny/navigasjon blir derfor litt feil. 
Men tror det per i dag er syndet på dette området, og at folk har brukt den til tab-visning. 

Hvilket bootstrap-eksempel tenkte du på? Det [eksemplet](https://v4-alpha.getbootstrap.com/components/buttons/#checkbox-and-radio-buttons) jeg fant bruker `input=radio` og navigerer med piltastene.

**Comment by erlendev** [comment]
@nutgaard 

Ok, jeg så på tilsvarende som det fra w3. Altså navbar, pills ol.

Utifra eksemplet ditt går jeg da utifra at dette egentlig er lagd for å være et skjemaelement. Kan se at det har vært litt uklart for folk, siden den baserer seg på onChange som egentlig åpner for det meste. Løses antageligvis med noe retningslinjer på komponenten, som vi kan legge inn i Guideline appen og storybook. Evt også legge det under skjema sine stories?

**Comment by erlendev** [comment]
Vi legger Toggle under Skjema i storybook-en og lukker saken.
