### ISSUE TITLE
componentWillReceiveProps warning

### ISSUE THREAD

**Issue by nutgaard** [navikt/aksel#539]
`EkspanderbartPanel` har avhengigheter til `react-collapse` og videre `react-motion`. 
Der blir `componentWillReceiveProps` brukt som er deprecated i nyeste versjon av react.

Ser heller ikke ut som react-motion blir aktivt forvaltet om dagen.
https://github.com/chenglou/react-motion/issues/569
https://github.com/chenglou/react-motion/pull/534

Foreslår at vi begynner å titte etter en erstattning for `react-collapse`.
https://react-collapsed.netlify.com/ ble nevnt, men krever react 16.8 (hooks)
https://www.npmjs.com/package/react-collapsible er ett annet alternativ som støtter react 15.x.x og 16.x.x

**Comment by thomasfl** [comment]
React-animate-height virker også som et alternativ til react-motion: https://github.com/Stanko/react-animate-height
