### ISSUE TITLE
Migrere til pakker med scope

### ISSUE THREAD

**Issue by Lillebo** [navikt/aksel#559]
Tenker det kan være greit om designsystemets komponenter tilbys under et eget scope, så slipper vi konflikter med det som allerede er publisert under `@navikt`. Foreslår `@navds` eller `@navfrontend`:

`nav-frontend-typografi` -> `@navds/typografi` / `@navfrontend/typografi` osv.

Ettersom dette uansett forutsetter at vi deprecater alle pakkene som migreres så burde vi kanskje benytte anledningen til å rename og skrive om alle komponentene til engelsk samtidig?

Dette kan vel også gjøres gradvis hvis vi begynner med pakker som ingen andre er avhengig av først.

**Comment by andnorda** [comment]
Vi planlegger å starte med dette nå, og en ikon-pakke er førstemann ut. Jeg foreslår navnet `@navfrontend/icons`.

Jeg foretrekker `@navfrontend` framfor `@navds` fordi frontend er mer deskriptivt for hva vi lager, mens designsystemet er et egennavn som jeg tenker har lettere for å endre seg. En forkortelse som `ds` har også lettere for å bli misforstått, så da ville jeg i så fall ha skrevet det helt ut, men `designsystemet` på norsk er kanskje heller ikke så kult. Blir det da `@navdesignsystem`? Nei, det føles rart. Jeg stemmer for `@navfrontend`.

**Comment by andnorda** [comment]
Hva med `@nav-frontend`?

**Comment by KenAJoh** [comment]
Under arbeid i @navikt/ds-react pakken
