### ISSUE TITLE
Fikse støtte for ikoner i Lenke

### ISSUE THREAD

**Issue by Lillebo** [navikt/aksel#568]
Utbedre støtte for ikoner i `Lenke`-komponenten på linje med `Knapp`. Legg til et sett med ferdig-konfigurerte ikonlenker:

- Eksternlenke/nyfanelenke
- Generisk fil-lenke
    - PDF-lenke
    - Word-lenke

osv.

**Comment by unorsk** [comment]
Lukker saken siden den ble løst og merget inn.
