### ISSUE TITLE
Spinner i Input

### ISSUE THREAD

**Issue by nutgaard** [navikt/aksel#572]
Flere som har demontrert behov for å kunne legge inn en spinner i `Input` komponenten.

![image](https://user-images.githubusercontent.com/1413417/66647346-f2ed5d80-ec28-11e9-96fa-26c201f819b5.png)

**Comment by Lillebo** [comment]
Hm, litt usikker på om den mest hensiktsmessige plasseringen av denne spinneren er ***inne*** i input-feltet 🤔 Noe av spinnerens funksjon er jo å ha noe å vise frem mens det man *egentlig* vil vise lastes. På den måten bidrar den til å dra brukerens oppmerksomhet mot det området som kommer til å forandre seg så snart lastingen er ferdig.

Klarer ikke helt å se noe scenario der man skulle ha behov for å vise spinneren og resultatene *samtidig*. For skjermbildet ovenfor så ville jeg kanskje heller løst det på denne måten:

![input-spinner](https://user-images.githubusercontent.com/74510/66915373-2ceba480-f019-11e9-9fb8-eb5db910ce5c.gif)

Mens jeg kanskje ville utelatt spinneren fullstendig hvis søket/filtreringen i resultatlisten skjer umiddelbart...

**Comment by unorsk** [comment]
> Mens jeg kanskje ville utelatt spinneren fullstendig hvis søket/filtreringen i resultatlisten skjer umiddelbart...

```
.delayed-spinner {
  animation: 200ms;
  animation-name: showAnimation;
  animation-fill-mode: forwards;
  visibility: hidden;
}

@keyframes showAnimation {
  99% {visibility: hidden;}
  100% {visibility: visible;}
}
```

Med noe slik ungår vi å vise spinneren for etterspørsel som tar mindre enn `200ms`
