### ISSUE TITLE
Mulighet for tooltips til etiketter

### ISSUE THREAD

**Issue by taniaholst** [navikt/aksel#577]
Trenger mulighet for å legge inn tooltips på etiketter.
Løses ved å legge inn attributtet "title" i EtiketterProps-klassen.

![image](https://user-images.githubusercontent.com/21334782/67088895-96e58480-f1a6-11e9-88ad-a45cffa60b34.png)

**Comment by Lillebo** [comment]
Dette skal allerede være fikset med #575 som ble merget i går. Prøv å oppdater `nav-frontend-etiketter` til siste versjon 🙂

**Comment by taniaholst** [comment]
Se der ja! Takker og bukker :)
