### ISSUE TITLE
Utbedre alle komponenter med "ref forwarding"

### ISSUE THREAD

**Issue by Lillebo** [navikt/aksel#587]
For å unngå videre bruk av deprecated `findDOMNode`.

**Comment by KenAJoh** [comment]
Siden refForwarding er mest praktisk å gjennomføre med functional-components, bør alle komponentene skrives bort fra klasser og da ta i bruk hooks? Har sett gjennom bekymringene rundt nødvendig oppdatering til React 16.8 i #660, men av de rundt 1800 dependents til React i navikt https://github.com/dependency-insights/npm/react/16.12.0/dependents?query=org%3Anavikt
Er bare rundt 60 av dem på en tidligere version enn 16.8, da flere av dem nav-frontend-moduler selv.
https://github.com/dependency-insights?query=org%3Anavikt+name%3Areact+version%3A%3C16.8.0
Blir også lettere å skrive seg bort fra eldre lifecycle metoder som nevnt i #603

**Comment by KenAJoh** [comment]
Under arbeid i @navikt/ds-react pakken
