### ISSUE TITLE
Omskrive til engelsk

### ISSUE THREAD

**Issue by Lillebo** [navikt/aksel#588]
- [ ] finne på nye engelske navn på alle norske komponenter
- [ ] skrive om kodebasen til engelsk

Ref. [diskusjon på Slack](https://nav-it.slack.com/archives/C60FFACN5/p1570620816033600)

**Comment by unorsk** [comment]
Nevner kun komponenter som er på norsk med scope-prefix `@navds`

`@navds/`
- alert-stripe
- expandable-panel
- label
- help-text
- icon-asset
- icon-button
- button (button-style)
- toggle (eller toggle-button?)
- close-button
- toggle-group
- link-panel? (link-panel-style)
- readmore (readmore-panel?)
- panel
- form
- speech-bubble
- progress-indicator for stegindikator
- tabel
- textarea
- assistant
- assistant-panel (kanskje icon-panel er også en god match siden hvilken som helst SVG kan brukes i den)

**Comment by nutgaard** [comment]
Tenker vi også kan ta inspirasjon fra bootstrap, material UI, semantic UI et. al.
Tenker vi da kanskje får en navngivning som er nogenlunde lik det folk er vant med fra før. Så kanskje det blir litt lettere å komme igang med nav-frontend da.

**Comment by Lillebo** [comment]
Designsystem-teamet har da blitt enige om å døpe om alt til engelsk 👍
https://github.com/navikt/Designsystemet/issues/113#issuecomment-573575072

**Comment by KenAJoh** [comment]
Under arbeid i @navikt/ds-react pakken
