### ISSUE TITLE
Fikse opp i props til Knapp

### ISSUE THREAD

**Issue by nutgaard** [navikt/aksel#591]
`KnappBaseProps` har idag `type: 'standard' | 'hoved' | 'fare' | 'flat'`. 
Denne gjør at man ikke kan ikke kan skrive `<Knapp type="submit" />`, men må heller bruke `htmlType`.

I en større omskriving bør vi endre slik at `type`-propen ikke blir brukt her, slik at vi slipper `htmlType`.

På generell basis kan `variant` erstatte `type` i de komponentene som idag har `type` for å sikre oss at vi ikke overskriver eksisterende html-attributter.

**Comment by Lillebo** [comment]
Her bør man også være obs på `form`-attributtet som nettopp ble lagt til på Knapp-komponenten. Dette attributtet er tenkt å få verdier ala `rund`, `kompakt` osv, og er ment å kunne fungere i kombinasjon med alle verdiene av dagens `type` - altså at man kan få en `rund hovedknapp` eller `kompakt flatknapp` osv.

Er enig i at `variant` er en god erstatning for `type`, men vi bør være obs på at disse attributt-navnene lett kan forveksles.

Det er flere komponenter som har lignende utfordringer: [Stegindikator](https://design.nav.no/components/stegindikator/technical#moduler), [ToggleGruppe](https://design.nav.no/components/togglegruppe/technical#moduler) og [ToggleKnapp](https://design.nav.no/components/toggleknapp/technical#moduler) har alle `kompakt: boolean` props. Mens [Veileder](https://design.nav.no/components/veileder/technical#moduler) og [VeilederPanel](https://design.nav.no/components/veilederpanel/technical#moduler) har litt av hvert: 😕

```tsx
fargetema?: 'normal' | 'suksess' | 'advarsel' | 'feilmelding';
type?: 'normal' | 'plakat';
kompakt?: boolean;
```

Vi bør kanskje ha en plan for hvordan vi løser situasjoner der komponenter har flere variasjons-typer som skal fungere i kombinasjon med hverandre. Og hvordan vil dette skalere?

```tsx
variant: 'standard' | 'hoved' | 'fare' | 'flat';
subVariant?: 'rund' | 'kompakt';
subVariant2?: 'stor' | 'liten';
```

osv. 🤔

**Comment by KenAJoh** [comment]
Er tatt til hensyn i nye pakker `@navikt/ds-react`
