### ISSUE TITLE
className mangler på EkspanderbartpanelProps

### ISSUE THREAD

**Issue by Lillebo** [navikt/aksel#592]
Ref. [Slack-diskusjon](https://nav-it.slack.com/archives/C6HJFRRMY/p1572354313054700)

**Comment by kjesvale** [comment]
Enkel fiks: https://github.com/navikt/nav-frontend-moduler/pull/594

Kunne ekstendet HTMLDiv sine props, men det kompliserer alt en del fordi komponenten da enten får flere hundre props eller må ta inn en wrapper-prop for alle div-propsene. Og man må forholde seg til to ulike definisjoner av `onClick` (på button og div). Er dette en OK fiks?

**Comment by Lillebo** [comment]
Det er nok en litt større jobb å skrive om disse interfacene til å utvide `div` ja 👍 Dette er en helt OK fiks inntil videre 🙂
