### ISSUE TITLE
Fleksibilitet i bruk av skjemaelementer

### ISSUE THREAD

**Issue by frodehansen2** [navikt/aksel#60]
Av og til trenger en litt variasjon i oppsettet av et Textarea (og evt. andre inputs) og label. Da hadde det vært fint å kunne sette label som valgfri prop til input, men at en da måtte sende inn id til det som som er label-elementet. Evt. andre løsninger.

**Comment by nutgaard** [comment]
Forslag til løsning:
 * Legge til en prop `noLabel` (eller ligende) som gjør at komponenten ikke renderer label. Og lar bruker håndtere dette selv.
 * label forblir required,

Hvis `noLabel` er satt blir `id` required.

**Comment by nutgaard** [comment]
Lukkes, tas opp igjen ved behov
