### ISSUE TITLE
Rydde i popover

### ISSUE THREAD

**Issue by nutgaard** [navikt/aksel#602]
**popover.tsx**:
* Komponenten bruker `React.createRef` som ikke finnes i gamle versjoner av react. Men peerDependencies er satt til `^15.4.2 || ^16.0.0`.
* Komponenten antar i dag at `popoverRef` er satt i `componentDidMount`. Hvorvidt dette kan garanteres er usikkert.
* Komponenten bruker i dag `ankerEl` for å styre synlighet, dette begrenser bruksområder for komponenten og kobler en prop til funksjonalitet på en uintuitiv måte. Synlighet bør styres av egen prop.
* Stor variasjon i hvordan indre funksjoner i komponenten er satt opp, e.g noen er arrow-functions mens andre er definert som klassefelt.
 
**popover-base.tsx**:
* non-null coercion av `posisjon` kan fjernes
* bruk `style` attributt bør unngås da det fjerner muligheten for å bruke styling-pakken uavhengig av react.

**Comment by Lillebo** [comment]
>Komponenten antar i dag at popoverRef er satt i componentDidMount. Hvorvidt dette kan garanteres er usikkert.

«[React guarantees that refs are set before componentDidMount](https://stackoverflow.com/questions/44074747/componentdidmount-called-before-ref-callback/50019873#50019873)».

>Stor variasjon i hvordan indre funksjoner i komponenten er satt opp, e.g noen er arrow-functions mens andre er definert som klassefelt.

Hm, klarer ikke helt å se noen indre funksjoner som er definert som klassefelt her?

>non-null coercion av posisjon kan fjernes

TS-kompilatoren klager på `possibly 'undefined'` uten denne 🤔

>bruk style attributt bør unngås da det fjerner muligheten for å bruke styling-pakken uavhengig av react.

Ser ikke helt hvordan denne komponenten skal kunne fungere uten å sette stiler på `PopoverBase`? Man kan jo fortsatt bruke style-pakken alene - men man mister jo da de dynamiske stilene som kalkuleres og settes av Popover.
