### ISSUE TITLE
Fjerne legacy lifecycle-metoder

### ISSUE THREAD

**Issue by Lillebo** [navikt/aksel#603]
Ref. https://reactjs.org/blog/2018/03/29/react-v-16-3.html#component-lifecycle-changes

Gjelder altså følgende metoder:
- `componentWillMount`
- `componentWillReceiveProps`
- `componentWillUpdate`

Som brukes i følgende komponenter:
- [ ] [CheckboksPanel](https://github.com/navikt/nav-frontend-moduler/blob/master/packages/node_modules/nav-frontend-skjema/src/checkboks-panel.tsx#L36)
- [x] [Popover](https://github.com/navikt/nav-frontend-moduler/blob/master/packages/node_modules/nav-frontend-popover/src/popover.tsx#L75) (fikset med #617)
- [ ] [Stegindikator](https://github.com/navikt/nav-frontend-moduler/blob/master/packages/node_modules/nav-frontend-stegindikator/src/stegindikator.tsx#L92)

Kan i første omgang skrives om til `UNSAFE_<metode>` for å fjerne konsoll-advarsler, men bør nok skrives om helt på sikt.

**Comment by KenAJoh** [comment]
CheckboxPanel og Stegindikator skrevet om til `UNSAFE_` i #747

**Comment by KenAJoh** [comment]
Under arbeid i @navikt/ds-react pakken
