### ISSUE TITLE
Popover not fixed when added in an input's label

### ISSUE THREAD

**Issue by NunoCardoso** [navikt/aksel#607]
![popover](https://user-images.githubusercontent.com/525528/68117772-8cddb880-fefe-11e9-99f2-c2ec764195a7.gif)

**Comment by Lillebo** [comment]
Hm 🤔 Could you provide a preview link to this screen? Or can I clone your repo and run this locally? It's a bit hard to troubleshoot this without the ability to take a closer look at the code :/

**Comment by NunoCardoso** [comment]
I found out the problem, I have bootstrap css imported, and it kind of conflicts a little, because of the popover class.

**Comment by Lillebo** [comment]
Ah, that explains it. Glad you figured it out 🙂
