### ISSUE TITLE
Hvorfor er Ekspanderbartpanel sin tittelProps obligatorisk?

### ISSUE THREAD

**Issue by alexander-svendsen** [navikt/aksel#614]
Ser at defaulten her er undertittel? 
Hvorfor er da tittelProps obligatorisk ? Er det ikke bedre at tittelProps er valgfritt? 

Vi har tidligere ikke hatt tittelProps når vi har brukt komponenten og nå får vi feilmelding ved bruk. Synnes Undertittel er en fornuftig default verdi og er hva vi bruker i alle scenarioene vi bruker ekspanderbartpanel

**Comment by Lillebo** [comment]
Hm, virker som denne ble gjort påkrevd allerede i [februar 2018](https://github.com/navikt/nav-frontend-moduler/commit/230bf8ea47b5bd16b1e62d7e7b91a483fa5984c1#diff-d0e17425155bdc77ab58d67586eac43e) - så litt rart hvis dere først får feilmelding på dette nå. 

Men jeg ser heller ikke noen grunn til at denne *bør* være påkrevd. Tar gjerne imot en PR som fikser den til optional 🙂

**Comment by alexander-svendsen** [comment]
Nylig lagt til typescript i prosjektet, så først nå vi ser feilen :P
