### ISSUE TITLE
Vurdere å gå bort fra lerna med x-npm pakker til én pakke med komponenter og én pakke med stiler

### ISSUE THREAD

**Issue by unorsk** [navikt/aksel#622]
Ønskes kommentarer med fordeler og ulemper og en god diskusjon :)

Vi kan også vurdere å:
- Redusere bruk av `typescript`
- Ta i bruk parcel (istedenfor CRA)

Hvis vi bestemmer å omskrive alt i to pakker, kan vi også:
- Kaste bort typografi-komponenter (og bruke kun CSS-stiler)
- Oversette alt til engelsk  https://github.com/navikt/nav-frontend-moduler/issues/588

**Comment by nutgaard** [comment]
Mange temaer her. Men skal prøve å gi mine synspunkter på en litt strukturert måte. :) 

**Lerna**:
Fordelen med flere pakker er at konsumentene kan selv styre hvilke endringer de tar inn i sin applikasjon. Om en modul har breaking-changes så kan de velge å ikke oppgradere denne frem til de har tid, men samtidig holde resten av pakkene oppdatert. Jeg mener derfor dette er en feature som er verdt å ta vare på. 

**Typescript**:
Antar at det er komponentene du sikter til, og forstår ikke helt hvorfor vi burde ville gjøre noe sånt?
Det er i dag mange som bruker typescript her, og for at et skal fungere så må type-definisjonene være definert. Man kan flytte definisjonene ut i egne `.d.ts` filer, men disse må uansett vedlikeholdes.

**Parcel**:
Tenker du på guideline-appen her? Eller generelt på hva som blir brukt rundt omkring på team?
Førstnevnte kan alltid vurderes, men jeg vet ikke om parcel støtter `require.context` som brukes en del i den appen.
Om det er sistnevnte så setter ikke nav-frontend noen begrensninger på hvilket verktøy man bruker for å bygge koden sin. 

**Typografi-komponenter**:
Tror ikke disse kan kastes selvom vi samler komponentene. Ser ihvertfall ikke hvorfor samlingen skulle ha noe å si?

**Engelsk**: 
Allerede oppe til vurdering, og tilknyttet https://github.com/navikt/nav-frontend-moduler/milestone/2
