### ISSUE TITLE
Legge inn linting (og spesielt a11y-linting) på eksempel-oppsettene

### ISSUE THREAD

**Issue by Lillebo** [navikt/aksel#627]
Det bør legges inn linting og da spesielt [a11y-linting](https://www.npmjs.com/package/eslint-plugin-jsx-a11y) i [eksempel-oppsettene](https://github.com/navikt/nav-frontend-moduler/tree/master/examples) for frontend-apps.

**Comment by unorsk** [comment]
Vet ikke om det er mye verdi i det. Siden det ikke er noen rocket science og sånne ting endrer seg nesten hver dag.

Men det er kanskje lurt å få på plass (og vedlikeholde) en liste av *best practices* og/eller *sjekklister* med lenker til sånne ting.
