### ISSUE TITLE
Tabell over komponent-props på design.nav.no gir ingen informasjon om extended props

### ISSUE THREAD

**Issue by Lillebo** [navikt/aksel#636]
Ref. [Slack-tråd](https://nav-it.slack.com/archives/C6HJFRRMY/p1578654628000700)

[Props-tabellen for `nav-frontend-modal`](https://design.nav.no/components/modal/technical#moduler) burde inkludere informasjon om at denne komponenten extender `react-modal`, og da støtter dens props i tillegg.

Dette gjelder flere komponenter.

**Comment by nutgaard** [comment]
`ModalProps` har en [liten kommentar](https://github.com/navikt/nav-frontend-moduler/blob/master/packages/node_modules/nav-frontend-modal/src/index.tsx#L17) som sier noe om dette. 

Tok en rask liten titt på hvorvidt den blir fanget opp av docgen, slik at vi lett kunne hente den ut. Dessverre ser det ikke ut til at den kommentaren blir med. Flyttes kommentaren til å ligge like over komponenten blir den tilgjengelig via `__docgen.description`, men det virker som en litt hacky løsning imho.

`react-docgen-typescript` har en del muligheter for customization, men hvorvidt det er mulig å få den til å plukke opp kommentaren har jeg ikke undersøkt.
