### ISSUE TITLE
Ha med tomme newlines i tekstområde

### ISSUE THREAD

**Issue by alexander-svendsen** [navikt/aksel#651]
Hvis jeg sender inn teksten:

```
1
2
3
4

5
6


7
```

I dagens tekstområde som bruker regexen:
`/[\r\n]+/`

Da får vi resultatet: 
`["1", "2", "3", "4", "5", "6", "7"]`

Kan vi skrive om regexen til:

`/\r?\n/`

Dette vil gi resultatet
`["1", "2", "3", "4", "", "5", "6", "", "", "7"]`

**Comment by nutgaard** [comment]
Det ligger an til endringer i tekstomrade-komponeten allerede, som jeg tror kanskje vil løse opp i deres problem også.

Eksemplet du beskriver vil per i dag gi følgende html:
```
<p class="typo-normal blokk-xs"><span>1</span></p>
<p class="typo-normal blokk-xs"><span>2</span></p>
<p class="typo-normal blokk-xs"><span>3</span></p>
<p class="typo-normal blokk-xs"><span>4</span></p>
<p class="typo-normal blokk-xs"><span>5</span></p>
<p class="typo-normal blokk-xs"><span>6</span></p>
<p class="typo-normal blokk-xs"><span>7</span></p>
```

Med de endringene som ligger i pipelinen så vil følgende html bli output; 
```
<p class="typo-normal blokk-xs">
1<br>
2<br>
3<br>
4
</p>
<p class="typo-normal blokk-xs">
5<br>
6
</p>
<p class="typo-normal blokk-xs">7</p>
```

Sånn sett vil markup mye nærmere matche intensjonen til input, uten at det legges til tomme paragrafer.

**Comment by Lillebo** [comment]
Løst med #658
