### ISSUE TITLE
https://design.nav.no/community 404: Siden finnes ikke

### ISSUE THREAD

**Issue by aksell** [navikt/aksel#653]
Hei, prøvde å klikke meg inn på `Bli med i diskusjonen` fra designsystemet-siden. 
![image](https://user-images.githubusercontent.com/22766894/73591686-0bdc9000-44f2-11ea-959a-f80f944089bd.png)

Der var det ingenting, ville si ifra i tilfelle det egentlig skal være noe der.

**Comment by Lillebo** [comment]
Tusen takk for at du melder ifra @aksell 🙂 Virker som vi har glemt å fjerne den lenken fra forsiden ja. "Bli med i diskusjonen" skulle egentlig lede brukeren til et forum, men vi har enda ikke rukket å lage noe på dette.

Inntil videre foregår diskusjonen for det meste i dette repoet (for frontend-tekniske ting), eller på Designsystem-repoet (for alt annet): https://github.com/navikt/designsystemet
