### ISSUE TITLE
Fjern normal og stroke varianter av Spinner, legg til blå variant av transparent

### ISSUE THREAD

**Issue by Lillebo** [navikt/aksel#656]

**Comment by unorsk** [comment]
Skal transparent-blå være default eller hva tanken var?

**Comment by unorsk** [comment]
Hvilke varianter vil vi beholde og hvilken er default?

**Comment by Lillebo** [comment]
Hm, faktisk litt usikker på om vi trenger å legge til en egen blå variant 🤔 Litt av poenget her er vel å forenkle og redusere alle ulike spinner-variantene våre uansett. Da tenker jeg kanskje at `negativ` kan være den nye defaulten, og så har vi `transparent` som eneste alternativ. Hva tror du?

**Comment by Lillebo** [comment]
Fikset av #676
