### ISSUE TITLE
Skjult fare for at en får duplikate ID'er

### ISSUE THREAD

**Issue by frodehansen2** [navikt/aksel#667]
https://github.com/navikt/nav-frontend-moduler/blob/22095f3d35e8c006ea1f2175f975e2c61dbc137b/packages/node_modules/nav-frontend-skjema/src/input.tsx#L65

En bør ikke bruke name som fallback for ID på input-element. Da er det risiko at en kan får duplikate ID'er i DOMen, som igjen kan forårsake rare feil. Dersom en ønsker å bruke name, bør en i så fall scope det, slik at risikoen er mindre for å få konflikt med andre elementer på siden. Aller helst bør name være påkrevd.

> Consider the name a required attribute (even though it's not). If an input has no name  specified, or name is empty, the input's value is not submitted with the form. (Disabled controls, unchecked radio buttons, unchecked checkboxes, and reset buttons are also not sent.)
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#htmlattrdefname

**Comment by frodehansen2** [comment]
Jeg stemmer for required prop, selv om det blir en breaking change for noen.

**Comment by Lillebo** [comment]
Enig 👍 

Bør kanskje sees litt i sammenheng med denne: https://github.com/navikt/Designsystemet/issues/65 - hvor vi kan gi litt hjelp til å finne `autocomplete`-vennlige navn til de mest kjente input-feltene.
