### ISSUE TITLE
fokus på ikon i alertstriper i IE

### ISSUE THREAD

**Issue by janerik-robertsen** [navikt/aksel#67]
IE har en sær oppførsel hvor den setter fokus på inline-svg'er hvis man bruker tab. Alle alertstripene bruker ikoner hvor dette forekommer.

Det kan fikses ved å sette focusable="false" på svg'en

Se: https://stackoverflow.com/questions/29393144/how-to-prevent-svg-elements-from-gaining-focus-with-tabs-in-ie11

**Comment by nutgaard** [comment]
Løst av #81 merged inn i #84
