### ISSUE TITLE
Skjemagruppe - fieldset?

### ISSUE THREAD

**Issue by frodehansen2** [navikt/aksel#68]
Er det vurdert å bruke fieldset for en skjemagruppe? Det virker logisk å ha en skjemagruppe som container for en checklist, men da skal en egentlig bruke fieldset med legend rundt de. Nå når komponenten krever tittel, og ikke rendres som fieldset/legend, må jeg legge fieldset/legend kode utenfor, og enda da opp med dobbel tittel.

**Comment by erlendev** [comment]
Jeg tenker at det er litt uheldig at SkjemaGruppe har title-feltet som required når den er implementert så generisk at den tar imot en vilkårlig liste av children-elementer/nodes. Det er vel det som gjør at `Fieldset` ikke passer bra inn som første child av `SkjemaGruppe` sånn som det er nå (som vel illustreres godt hos deg @frodehansen2 med dobbel tittel).

Tanken med `SkjemaGruppe` er vel at den skal kunne wrappe hvilke sammensetninger av form-elementer som helst? Kjenner ihvertfall at jeg er litt skeptisk til å legge inn noe logikk i `SkjemaGruppe` for å rendere fieldset og legend dynamisk basert på children-elementer hvis det kun gir mening i radio/checkbox-gruppesammenheng. Kan man ikke heller sette title til optional og la det være opp til utviklerne å sørge for at title vs. fieldset/legend blir brukt riktig i `SkjemaGruppe`?

**Comment by frodehansen2** [comment]
Enig at det er unødvendig å legge logikk for å rendre fieldset eller noe annet. Optional vil fungere bra tror jeg. Tittel rendres vel bare i en div også, så det er ikke noe semantisk som forsvinner dersom den ikke sendes inn?

**Comment by erlendev** [comment]
Nei, det skal det ikke være. Har også avklart med design internt at dette er ok, så jeg tenker at vi går for det :)
