### ISSUE TITLE
Få kjørt opp storybook på GitHub-pages 

### ISSUE THREAD

**Issue by erlendev** [navikt/aksel#7]
Vi kan nøye oss med å deploye det ut på denne i første omgang:

https://navikt.github.io/nav-frontend-moduler/

Inntil vi får ordnet med et eller annet subdomene, ala frontend.nav.no.

**Comment by DeamonDavid** [comment]
Betyr det at den er ute nå?

**Comment by nutgaard** [comment]
Jupp :)
https://navikt.github.io/nav-frontend-moduler

**Comment by DeamonDavid** [comment]
Gull! Hvor er det man kan rapportere f.eks #uu-feil etc?

**Comment by nutgaard** [comment]
Github har "issues" som alle kan opprette, så tror det er greiest å ta det der. På den måten får vi samlet alt på ett sted. ☺️ Eks #13

**Comment by DeamonDavid** [comment]
Da tror jeg jeg skal ha klart å plassere en issue riktig, #14 :-)
