### ISSUE TITLE
StegIndikator with autoReponsiv throws getBoundingClientRect errors

### ISSUE THREAD

**Issue by NunoCardoso** [navikt/aksel#705]
I am getting errors when autoResponsiv is on. 

When resizing the page, it seems that this.list becomes undefined, so the getBoundingClientRect function call fails. 
![stegIndikator](https://user-images.githubusercontent.com/525528/78232913-3f796d80-74d5-11ea-8566-5724e0199a3c.gif)

**Comment by NunoCardoso** [comment]
My guess is that it has to do with the ref, which is deprecated in that callback function style, and should be replaced with React.createRef();

**Comment by Lillebo** [comment]
Looks like the auto-adjustment actually works despite sometimes throwing `undefined` on the list ref. I think adding a simple check to see if `this.list` is falsy might be a quick fix here.

I don't think callback refs are deprecated in React just yet. If we rewrite this to use `React.createRef()` instead we would also need to bump the React dependency to `16.3+`. I think that is a change more suited for [V - next](https://github.com/navikt/nav-frontend-moduler/milestone/2). Somewhat related to #587.
