### ISSUE TITLE
Manglende state i checkbox: Valgt (checked) checkbox som er disablet

### ISSUE THREAD

**Issue by etse** [navikt/aksel#71]
Tilfellet checkbox er valgt (checked) men disablet ser ut til å mangle. Vi burde få inn denne staten også.

**Comment by nutgaard** [comment]
Valgt som i fokus, eller valgt som i checked?

**Comment by etse** [comment]
Spesifiserer (oppdater originalpost). Men mente altså at den er checked, men man har ikke mulighet til å avvelge den. Bruksområder er f.eks. hvor du har en gruppe checkbokser og du må minst ha valgt X alternativer.

**Comment by erlendev** [comment]
Litt usikker på om jeg har forstått use case'n her riktig, er det det at man ønsker å disable checkboxene i gruppa idet X antall checkboxer er huket av, for å unngå at det blir gjort flere valg enn X, for så å kunne avvelge igjen de som man har huket av? Om det må løses sånn så tenker jeg ihvertfall at man disabler de andre valgene (som ikke er huket av), istedetfor å åpne for å endre checked-state på en checkbox som er disabled. 

... Men her er det mulig jeg har misforstått? 😄

**Comment by etse** [comment]
Vi har en tabell med et sett med kolonner, hvor man i komponenten vår skal kunne velge hvilke kolonner som vises ved å velge/avvelge checkokser. 2 Kolonner skal alltid være der, og derfor kan man ikke fjerne de. Men våre funksjonelle designere ønsker at de fortsatt skal vises som alternativer i listen for å tydeliggjøre at det du velger er hvilke kolonner som er synlige.

Dette burde bare være en enkel stylingregel som må legger til for tilfellet "disabed and checked". Christian har fikset dette i FO-portefølje, så vi kunne kanskje fått inn hans fiks i nav-frontend.

**Comment by nutgaard** [comment]
Løst
