### ISSUE TITLE
Forbedre valideringen for FnrInput

### ISSUE THREAD

**Issue by KenAJoh** [navikt/aksel#724]
FnrInput sin feilmelding blir bare lest opp av skjermleser(voiceover) en gang og da ikke repetert. Dette betyr at brukerene får lest opp "Ugyldig fødselsnummer" når de skriver det første sifferet, men ikke når de har fylt ut alle 11 sifrene. 
Dette er et problem som da evt må løses på alle skjemakomponenter.

**Comment by Lillebo** [comment]
Tror dette kan fikses ved å bruke `aria-describedby` og gi det samme ID-verdi som settes på `aria-errormessage` 🤔

Dette gjelder da alle skjema-komponentene våre.

**Comment by KenAJoh** [comment]
Hørte med David Hole om dette problemet og repetering av feilmelding var ikke ønsket. Han mente heller man måtte være smartere med når man setter en feilmelding, da helst først når det faktisk har skjedd en feil. Løsning for designsystemet er da eventuelt å utbedre valideringskoden i FnrInput + skrive oppfordring på input-elementer om å skrive smartere kode for validering av input.

**Comment by nutgaard** [comment]
Vi har rettningslinjer for validering [her](https://design.nav.no/patterns/form-validation). Vet ikke om den er oppdatert med siste nytt. Men tenker ihvertfall at FnrInput burde følge de valideringsreglene der når vi først tok inn en komponent som gjør denne typen selv-validering.
