### ISSUE TITLE
Ugyldig webpack config eksempel.

### ISSUE THREAD

**Issue by mathiasror** [navikt/aksel#751]
https://github.com/navikt/nav-frontend-moduler/tree/master/examples/webpack

Dette fungerer ikke med nyere versjoner av webpack.

Mer spesifikt, dette er ugyldig: `'less-loader?{"globalVars":{"nodeModulesPath":"\'~\'", "coreModulePath":"\'~\'"}}'`

**Comment by nutgaard** [comment]
Tror ikke `nodeModulesPath` eller `coreModulePath` er i bruk noe mer, så prøv å kjør uten. ;)

**Comment by nutgaard** [comment]
@KenAJoh @Lillebo 
Hva tenker dere om eksempel-oppsettene fremover. Føler det å vise hvordan det kan gjøres med CRA siden det er relativt standard her på huset. Men de andre variantene kan vi kanskje kvitte oss med?

**Comment by KenAJoh** [comment]
Lager et nytt og oppdatert oppsett for Webpack nå da et barebones bootstrap kan være greit å ha, men browserify og parcel kan nok fjernes ja.
