### ISSUE TITLE
Title på chevron

### ISSUE THREAD

**Issue by henninghaakonsen** [navikt/aksel#761]
Hovertekst på chevron er "Chevron". Bør være "åpne"/"lukk" eller konfigurerbare avhengig av state.

**Comment by KenAJoh** [comment]
Hei, har du noen spesifikke eksempler der vi kan se dette? Chevron-komponenten er i grunn bare en tom `<i>`-tag med CSS, der brukeren velger hvordan interaksjonen skal være.

**Comment by henninghaakonsen** [comment]
I ChevronSvg.js settes title:
        react_1.default.createElement("title", null, "Chevron"),

Ikke sikkert dere gjør dette med vilje, men det ser hvertfall litt rart ut. Hvorfor er dette egentlig en `<i/>`?
Tenker det beste er kanskje hvis alle html props'ene blir eksponert til sluttbruker. Det gjøres i flere andre komponenter hvertfall :) Da kan man sende inn title selv.

**Comment by KenAJoh** [comment]
Er det riktig at det nå er snakk om https://github.com/navikt/datovelger ? Om så ligger denne under https://design.nav.no/components/other og da ikke direkte støttet av Designsystemet. Anbefaler da å overføre issuet til det repoet. 😃 

Når det kommer til hvorfor `<i>` er brukt er jeg ikke helt sikker. Antar det har noe med UU å gjøre, samt denne beskrivelsen fra w3schools: `The <i> tag is often used to indicate a technical term, a phrase from another language, a thought, a ship name, etc.`.

**Comment by henninghaakonsen** [comment]
Nei, det gjelder: https://github.com/navikt/nav-frontend-moduler/tree/master/packages/node_modules/nav-frontend-chevron

**Comment by KenAJoh** [comment]
Finner ingen fil chevronSvg.js i designsystemet, men finner denne i navikt/datovelger 
https://github.com/navikt/datovelger/blob/3847671c9787097c97518b1e38a1fc0fc92f95e7/src/datovelger/elementer/ChevronSvg.tsx#L31
Som da blir transpilert til chevronSvg.js og inneholder koden `react_1.default.createElement("title", null, "Chevron")`
Ser ut som de da ikke bruker designsystemet sin chevron, men en egen i SVG format.

**Comment by henninghaakonsen** [comment]
Nei ChevronSvg.js er jo den transpilerte fila fra chevron pakken. Den konsumentene henter fra npmjs.
Dere må endre på chevron pakken til å tillate title prop, eventuelt extende html default props.

**Comment by nutgaard** [comment]
`ChevronSvg` eksisterer som @KenAJoh sier ikke i nav-frontend-chevron. Verken som typescript fil, eller transpilert fra chevron pakken.

Hele kildekoden kan du titte på her; https://github.com/navikt/nav-frontend-moduler/blob/master/packages/node_modules/nav-frontend-chevron/src/chevron.tsx#L47

Men det eneste som gjøres er dette; `return <i className={cls(type, stor, className)} {...props} />`

**Comment by henninghaakonsen** [comment]
Ahh, ser nå at noen (TM) har cowboya inn chevron via datovelger. Uansett trenger vi å sette title og det ser ikke ut til at nav-frontend-chevron støtter det?

**Comment by nutgaard** [comment]
Det stemmer forsåvidt at `<Chevron />` ikke støtter `title` attributtet, men det bør den heller ikke gjøre IMHO.
Dette pga problemer med tilgjengelighet, e.g fungerer dårlig for skjermlesere og på touch-skjermer f.eks.

Om dere uansett må ha det så ville jeg vurdert å legge det interaktive elementet fremfor selve `<i>` elementet. 
E.g
```
<button title="awesome title here">
  Click here 
  <Chevron />
</button>
```

Om det er snakk om å gjøre endringer på chevronen fra nav-datovelger så bør det tas med de som forvalter det repoet.

**Comment by henninghaakonsen** [comment]
Ja, jeg _tror_ noen fant en rask vei til en fiks her og har dratt inn chevron fra nav-datovelgeren. Skriver nok om til å bruke den fra nav-frontend-chevron. @frodehansen2 kjenner du til hvorfor chevron har title `Chevron` i nav-datovelgeren? Bør vel også endres der tenker jeg :)
