### ISSUE TITLE
Uncaught TypeError i Ekspanderbartpanel

### ISSUE THREAD

**Issue by Lars-Andreas** [navikt/aksel#766]
Jeg får en error i konsollen når jeg tabber meg ut av et Ekspanderbartpanel. 

![image](https://user-images.githubusercontent.com/36694755/89191315-0a744900-d5a3-11ea-88d5-ea76c39c740b.png)

**Comment by nutgaard** [comment]
#767 løser problemet.

I mellomtiden så er effekten av feilen at man kan tabbe ut av panelet mens lukke-animasjonen er pågående. Er en snål edge-case med nøstede paneler som er årsaken til at vi vil hindre det, se #48
