### ISSUE TITLE
ModalWrapper not exposing all properties of react-modal

### ISSUE THREAD

**Issue by alexladerman-nav** [navikt/aksel#772]
Modal won't close onRequestClose because focus is returned to the DOM element that triggered the opening of the modal with onFocus in the first place, thereby reopening the modal. AFAIK this (and other) behaviour can be switched off in react-modal, yet the flag has not been exposed in the wrapper. See shouldReturnFocusAfterClose http://reactcommunity.org/react-modal/

**Comment by nutgaard** [comment]
Using `onFocus` to trigger a modal seems like a a11y-pitfall to me, so I would really reconsider making it an explicit action (e.g `click`). Perhaps there are some scenarios where this is appropriate, but none comes to mind. :/ 

In terms of exposing `shouldReturnFocusAfterClose` you simply need to update `react-modal` and `@types/react-modal` both of which are peerDependencies of `nav-frontend-modal` and the newest versions are within the accepted range.
