### ISSUE TITLE
Hjelpetekster - lukke ved Esc og når annen åpnes?

### ISSUE THREAD

**Issue by frodehansen2** [navikt/aksel#78]
Har det vært diskutert mulighet for at en kan ha kun en hjelpetekst åpen samtidig? Nå må en lukke hver enkelt. En bør også vurdere mulighet for lukking vha Esc tasten.

**Comment by ingvilin** [comment]
De gamle søknadsdialogene oppfører seg også slik - at man må lukke hver enkelt. Hvis det endres så burde det vel endres for de gamle også?

**Comment by nutgaard** [comment]
Er det et funksjonelt krav som treffer dere @frodehansen2 ? Eller var det mer at du synes det virket rart?

**Comment by frodehansen2** [comment]
Kun at vi har fått noen tilbakemeldinger på det, så ikke noen funksjonelle krav (enda).

**Comment by nutgaard** [comment]
Tror vi titter litt på denne.

Ting som bør/må være med: 
- Klikk på utsiden for å lukke
- Escape for å lukke

**Comment by frodehansen2** [comment]
Denne er fikset gjennom PR #176 som er merget inn i master
