### ISSUE TITLE
Dokumenterer variable-export fra nav-frontend-core

### ISSUE THREAD

**Issue by nutgaard** [navikt/aksel#780]
Er nå mulig å skrive `import vars from 'nav-frontend-core'` og få tilgang til alle less-variablene i js/ts.

Men mangler dokumentasjon på design.nav.no og vi trenger kanskje ikke easter-egg på akkurat dette område.

**Comment by KenAJoh** [comment]
Vil ikke bli gjort før ny dokumentasjonsside er på plass og core evt deprecates.
