### ISSUE TITLE
Mulighet for "Lukke"-knapp/chevron nederst i Ekspanderbartpanel 

### ISSUE THREAD

**Issue by rittikdey** [navikt/aksel#786]
Dersom innholdet i `nav-frontend-ekspanderbartpanel` blir veldig langt (over 40 linjer) ser vi et behov for å kunne lukke det ekspanderbare panelet når man har scrollet til bunn, uten å måtte scrolle helt opp igjen.

Hadde vært kjekt å ha en property hvor man kan velge om man ønsker dette eller ikke.

Har løst det ved å bruke `EkspanderbartpanelBase` og sette `apen`-propertyen i komponentens state, og i tillegge en `onClick` på panelet for å toggle state.  Lagt til en midtstilt "Chevron" nederst som setter state.

<img width="916" alt="Screenshot 2020-09-22 at 10 25 44" src="https://user-images.githubusercontent.com/59570405/93886378-9d994780-fce5-11ea-9e24-48eb112d00bf.png">

Se kode her:
https://github.com/navikt/pensjon-selvbetjening-opptjening-frontend/blob/master/src/components/elements/InntektPanel/InntektPanel.js

**Comment by KenAJoh** [comment]
Vi har notert oss ønsket for løsningen, men inntil videre velger vi å vente til vi ser at dette er noe flere har behov for. I mellomtiden kan det være lurt å høre med UU-teamet på slack for å høre om løsningen er UU-kompatibel.
