### ISSUE TITLE
Hjelpetekster - focus og mobil (fullskjerm)

### ISSUE THREAD

**Issue by frodehansen2** [navikt/aksel#79]
Dersom en får mobil visning hvor hjelpetekster legger seg over hele skjermen, kan en bruke tab for å komme seg bort fra hjelpetekstkomponenten. Usikker på hvor alvorlig det er gitt at en ikke tabber på mobil.

**Comment by nutgaard** [comment]
Tror ikke vi gidder å spesialhåndtere denne før det blir ett problem.
