### ISSUE TITLE
Forslag: Justere logo- og tittel-alignment på designsystemnettsiden

### ISSUE THREAD

**Issue by macbruker** [navikt/aksel#863]
Vet ikke om det er vanlig at utenforstående oppretter issues her, men jeg prøver meg 🙂 

Etter fagpraten om designsystem hos Netlife har jeg brukt litt tid på å bli bedre kjent med designsystemet deres. Imponerende og inspirerende! 

Dette er ikke et viktig forslag, men jeg ser en mulighet for å justere alignment for logo og tittel i designsystemet.
![nav-design-align](https://user-images.githubusercontent.com/1032194/98091319-8ec9b700-1e85-11eb-977a-e44379eb166a.png)

**Comment by KenAJoh** [comment]
Hei, vi setter pris på all hjelp og tips vi kan få, uansett hvor det kommer fra! 😄 
Dette er et godt forslag og laget en liten PR på det her #866
