### ISSUE TITLE
nav-frontend-ikoner-assets: Feil type i svg focusable-attribute

### ISSUE THREAD

**Issue by terjeofnorway** [navikt/aksel#88]
Ser ut til at SVG for ikoner i `nav-frontend-ikoner-assets` setter inn en faktisk Boolean i focusable-attribute, mens [W3C spesifiserer String](https://www.w3.org/TR/SVGTiny12/interact.html#focus). Dette trigger en warning i nyere React-versjoner.

Gjelder [nav-frontend-ikoner-assets/src/index.js](https://github.com/navikt/nav-frontend-moduler/blob/master/packages/node_modules/nav-frontend-ikoner-assets/src/index.js), linje 111-128.

trigger en warning:
`focusable={false}`

kjapp test i koden trigger ikke lenger warning:
`focusable="false"`

**Comment by nutgaard** [comment]
Vi har en fork av biblioteket som gjør dette. Så må få ut en ny versjon av det biblioteket.

**Comment by nutgaard** [comment]
Løst i #96
