### ISSUE TITLE
Lang placeholdertekst i textarea dekkes av tellerteksten

### ISSUE THREAD

**Issue by otenav** [navikt/aksel#89]
Om man har en lang placeholdertekst i textarea, så kan tellerteksten overlappe placeholdertekst.

![textarea](https://user-images.githubusercontent.com/29566394/30953137-e282acd6-a42a-11e7-8f3f-4f5460642497.png)

**Comment by frodehansen2** [comment]
I digisos har vi tatt bort visningen av antall tegn igjen frem til en nærmer seg grensen for hva som er lov. Noen brukere såg dette tallet som en forventning på hvor mye som skulle skrives inn, så da vi hadde 800 tegn, var brukeren på god vei til å fylle ut 800 tegn. 
En kan kanskje vurdere å ha dette som standard oppførsel for nav-frontend-moduler? 

Høyden på feltet beregnes vel bare ut fra verdien, så dersom en har lang placeholder-tekst, må en sette min-height på feltet i tillegg/eller bruke placeholder-tekst i tillegg i beregningen?

**Comment by nutgaard** [comment]
Standard oppførsel er alt definert i nav-frontend. 😛 Men om dere har erfaringer med at den bør endres så er det noe vi bør ta opp med designsystem-teamet.

Når det kommer løsning på selve issuet så stemmer nok jeg for å bruke placeholder-teksten i beregningen.

**Comment by erlendev** [comment]
Høres naturlig ut å ta med placeholder-tekst i beregningen av høyden ja. Kan fikse en PR på det jeg.
