### ISSUE TITLE
Behov for describedby i input

### ISSUE THREAD

**Issue by otenav** [navikt/aksel#91]
Vi har et behov for å legge til "%" rett etter et input felt:
![prosent](https://user-images.githubusercontent.com/29566394/31071032-d94080ae-a762-11e7-8651-75d9e7bd17bf.png)

Hvis vi kan sende inn describedby="%" som props til input kan vi gjøre følgende i Input.js:
```
<input type="text" aria-describedby="input-xxx-description" />
<span class="input-description" id="input-xxx-description">%</span>
```

**Comment by erlendev** [comment]
Vi må først og fremst forsikre oss om at det er denne måten man ønsker å løse input for prosent/stillingsbrøk på i NAV sine løsninger. Har gitt beskjed om behovet og gir beskjed når jeg hører noe mer.

**Comment by erlendev** [comment]
Dette er ikke forankret NAV design for input for %. Forstår det som at dette uansett skal redesignes og lukker derfor saken.
