### ISSUE TITLE
[NEW] Compatibility with less 4.0.0

### ISSUE THREAD

**Issue by NunoCardoso** [navikt/aksel#929]
## Beskriv forespørselen

Less 4.0.0 har "breaking changes". Den som bryter nå er:

https://github.com/less/less.js/releases/tag/v4.0.0

Parentheses required for mixin calls
This aligns it with syntax for calling detached rulesets.

Example

.mixin() {}
.mixin;  // error in 4.0

## Hvilken funksjon vil dette har for bruker?

Bruker kan brukers nyeste versjoner av less

## Eksempler/Tilleggsinformasjon 

Det bryter inn koden min på textarea.less med:

.textareamirror {
  .typo-normal-mixin();
  .skjemaelement__input; <-- here

Jeg tror at vi må sjekke alle mixins så at det virker med less 4.0.0

**Comment by KenAJoh** [comment]
Har gått gjennom alle stilene, men ser ut som det bare trengtes fiksing i textarea.less. Skal være fikset snart 🔨
