### ISSUE TITLE
Fokus-radius (hit-area) på radioknapper ligger for høyt oppe til venstre

### ISSUE THREAD

**Issue by erlendev** [navikt/aksel#98]

**Comment by frodehansen2** [comment]
Har sett på saken, og det virker til at feilen nå kun gjelder dersom label ikke vises - dvs. under storybook "Skjulte labels". Usikker om en da skal fikse det. I så fall kan en løsning være å sette min-height på label til 1em eller noe tilsvarende.

**Comment by nutgaard** [comment]
Har ett tilfelle av skjulte labels i en FO-løsning. Så jeg kan ta en titt der i morgen for å se om det treffer oss i noen særlig grad. Hvis ikke så tenker jeg vi lukker denne.  

Edit: 
Verifisert at det ikke var noe problem med dette i FO-løsningen.
@erlendev Bare lukke denne?

**Comment by nutgaard** [comment]
Lukkes
