### ISSUE TITLE
Popover plassering 

### ISSUE THREAD

**Issue by taniaholst** [navikt/aksel#987]
## Hvilken av tjenestene våre gjelder det?
- [X] `Komponenter`
- [ ] `Stiler`
- [ ] `Ikoner`
- [ ] `Annet`

## Beskriv feilen/problemet

`updatePosition` kalles ikke når man renderer komponenten med `ankerEl`. 

## Mulig løsning
Alltid rendre Popover-komponenten, og bytte ankerEl mellom `null` og `html-elementet`, for da kjøres `componentDidUpdate` som kaller `updatePosition`.

**Comment by KenAJoh** [comment]
Dette er et problem vi har løst i den nye `popover`-komponenten vi har laget. Den er fortsatt i beta og ikke dokumentert, men om ønsket kan den fortsatt tas i bruk.

```bash
yarn add @navikt/ds-react @navikt/ds-tokens @navikt/ds-css
```
Importere tokens, legger css-variabler på `:root` (høyt oppe i dom), for IE11 støtte kan denne brukes https://jhildenbiddle.github.io/css-vars-ponyfill/#/

`import "@navikt/ds-tokens"`


Importere react komponent:
`import { Popover } from '@navikt/ds-react`

Eksempel på bruk her: https://github.com/navikt/nav-frontend-moduler/blob/master/%40navikt/ds-react/popover/stories/popover.stories.tsx

Popover-kode her (for props): 
https://github.com/navikt/nav-frontend-moduler/blob/master/%40navikt/ds-react/popover/src/Popover.tsx
