### ISSUE TITLE
[BUG] Checkbox-stil overskriver i tabell

### ISSUE THREAD

**Issue by ninakjek** [navikt/aksel#997]
## Hvilken av tjenestene våre gjelder det?

- [ ] `Komponenter`
- [X] `Stiler`
- [ ] `Ikoner`
- [ ] `Annet`

## Beskriv feilen/problemet

Checkbox får styling 
```
width: 24px;
        text-indent: -9999px;
        padding: 0;
```
og label skjules

## Steg for å reprodusere problemet

(skriv her.)

## Eksempel/Tilleggsinformasjon

```
 Hvis mulig, legg gjerne til kode her, evt lenke til kode i repo
```
https://github.com/navikt/familie-ba-sak-frontend/pull/762/files#diff-ffe19102a0eb3ced1673f14ca1d991fe9295b214b10a4ee1403423aedc20ae23R32

**Comment by KenAJoh** [comment]
Hvis jeg har skjønt det riktig ønskes det at label-teksten skal vises i samme rute som checkboksen her?

**Comment by ninakjek** [comment]
Ja, normalvisning som her: https://design.nav.no/components/checkbox
 vi bruker den i en "ekspandert" rad, så om det blir helt feil mtp generell bruk i tabell kan vi bare overskrive altså :)
